---
title: "Analysing Subcluster Canonical Pathway GSEA Results and Leading Edge Genes"
output: html_document
---

Most differentially expressed pathways

```{R}
library(reshape2)
library(dplyr)
library(tidyr)
library(vroom)
library(pheatmap)

#Cell_Type <- gsub("_TREATED_vs_CTRL_GSEA_Sig_Genesets.tsv","",list.files("../Files/Subclusters_GSEA/"))
files <- list.files("../Files/Subclusters_GSEA", full.names = TRUE, pattern = "*_ILB_vs_HC_GSEA_SigBHCorrection_Genesets.tsv")
files <- files[grep("PD_and",files,invert = TRUE)]
GSEA_Aggr_Table <- vroom(files, id = "Cell_Type")
GSEA_Aggr_Table$Cell_Type <- gsub("../Files/Subclusters_GSEA/|_ILB_vs_HC_GSEA_SigBHCorrection_Genesets.tsv","",GSEA_Aggr_Table$Cell_Type)
#GSEA_Aggr_Table$Cell_Type <- #gsub("GLU_Cajal_Retzius","Cajal-Retzius",GSEA_Aggr_Table$Cell_Type)
```


```{R}

write.table(GSEA_Aggr_Table, file = "../Files/ILB_vs_HC_GSEA_AssignedClusters_AggregateTable.csv", quote = FALSE, row.names = FALSE,col.names = TRUE, sep = ",")

```


```{R}

GSEA_Aggr_Table_PvalSorted <- GSEA_Aggr_Table[order(GSEA_Aggr_Table$padj),]

write.table(GSEA_Aggr_Table_PvalSorted, file = "../Files/ILB_vs_HC_GSEA_AssignedClusters_AggregateTable_PvalSorted.csv", quote = FALSE, row.names = FALSE,col.names = TRUE, sep = ",")

GSEA_Top_Pathways <- unique(GSEA_Aggr_Table_PvalSorted$pathway)[1:30]

```




```{R}
library(rlist)
Heatmap_Matrix <- list()
for (i in unique(GSEA_Aggr_Table$Cell_Type)) {
  temp_table <- GSEA_Aggr_Table[GSEA_Aggr_Table$Cell_Type %in% i,]
  index <- which(GSEA_Top_Pathways %in% temp_table$pathway)
  if (length(index) == 0) {
    NES_subtable <- as.data.frame(cbind(rep(i,length(GSEA_Top_Pathways)),GSEA_Top_Pathways,rep(0,length(GSEA_Top_Pathways))))
    colnames(NES_subtable) <- c("Cell_Type","pathway","NES")
  }
  else {
    NES_subtable <- temp_table[temp_table$pathway %in% GSEA_Top_Pathways,]
    NES_subtable <- NES_subtable[,c(1,2,7)]
    if (length(NES_subtable$Cell_Type) == 7){
      NES_subtable <- NES_subtable
    }
    else{
      temp_table2 <- as.data.frame(cbind(rep(i,length(GSEA_Top_Pathways[-index])),GSEA_Top_Pathways[-index],rep(0,length(GSEA_Top_Pathways[-index]))))
      colnames(temp_table2) <- c("Cell_Type","pathway","NES")
      NES_subtable <- rbind(NES_subtable,temp_table2)
    }
  }
  Heatmap_Matrix <- list.append(Heatmap_Matrix,NES_subtable)
}

Heatmap_Matrix <- do.call("rbind", Heatmap_Matrix)
```




```{R}
Heatmap_Matrix$NES <- as.numeric(Heatmap_Matrix$NES)
Heatmap_Matrix <- dcast(data = Heatmap_Matrix,formula = Cell_Type~pathway,fun.aggregate = sum,value.var = "NES")
rownames(Heatmap_Matrix) <- Heatmap_Matrix$Cell_Type
Heatmap_Matrix <- Heatmap_Matrix[,-1]


```

doublets: 10,25,28,29

`10` = "GLU_Neurons_6"
`25` = "GABA_Neurons_8"
`28` = "GABA_Neurons_9",
`29` = "GLU_Neurons_12"


```{R}

SubclusterSplitCaseNumbersTable <- read.delim("../Files/Subcluster_SplitCase_NumbersTable.tsv")

Assigned_Clusters <- unique(SubclusterSplitCaseNumbersTable$Var1)

excluded_cells <- Assigned_Clusters[-which(Assigned_Clusters %in% rownames(Heatmap_Matrix))]

#excluded_cells <- gsub("Endothelial_Cells","Endothelial_Cells_and_Microglia",excluded_cells)

#rownames(Heatmap_Matrix) <- gsub("Endothelial_Cells","Endothelial_Cells_and_Microglia",rownames(Heatmap_Matrix))

for (ec in excluded_cells) {
  Heatmap_Matrix <- rbind(Heatmap_Matrix,rep(0,ncol(Heatmap_Matrix)))
  rownames(Heatmap_Matrix)[nrow(Heatmap_Matrix)] <- ec
}

```


```{R}

rownames(Heatmap_Matrix) <- gsub("_"," ",rownames(Heatmap_Matrix))

rownames(Heatmap_Matrix) <- gsub("TEMRA T Cells","Unknown Immune Cells",rownames(Heatmap_Matrix))

rownames(Heatmap_Matrix) <- gsub("Unknown Cluster 66","Unknown Cluster 1",rownames(Heatmap_Matrix))

Cluster_Order <- c("GLU Neurons 1", "GLU Neurons 2", "GLU Neurons 3", "GLU Neurons 4", "GLU Neurons 5", "GLU Neurons 6", "GLU Neurons 7", "GLU Neurons 8", "GLU Neurons 9", "GLU Neurons 10", "GLU Neurons 11", "GLU Neurons 12", "GLU Neurons 13", "GLU Neurons 14", "GLU Neurons 15", "GLU Neurons 16", "GLU Neurons 17", "GLU Neurons 18", "GLU Neurons 19", "GLU Neurons 20", "GABA Neurons 1", "GABA Neurons 2", "GABA Neurons 3", "GABA Neurons 4", "GABA Neurons 5", "GABA Neurons 6", "GABA Neurons 7", "GABA Neurons 8", "GABA Neurons 9", "GABA Neurons 10", "GABA Neurons 11", "GABA Neurons 12", "GABA Neurons 13", "GABA Neurons 14", "GABA Neurons 15", "Astrocytes", "Oligodendrocytes", "OPCs", "Microglia", "Endothelial Cells 1", "Endothelial Cells 2", "Unknown Immune Cells", "Unknown Cluster 1")

Heatmap_Matrix <- Heatmap_Matrix[match(Cluster_Order,rownames(Heatmap_Matrix)),]

```



```{R}
library(ggplot2)

MYPalette <- colorRampPalette(c("magenta","#C228C8","#813384","#000000","#817E3E","#BEB72F","#FFF300"))(200)

pheatmap(Heatmap_Matrix, border_color = "gray", color = MYPalette, cellwidth = 10, cellheight = 10, breaks = seq(from=-2,to=2, length.out=200), cluster_cols = TRUE, cluster_rows = TRUE)

GSEA_Human_PFC_Heatmap <- pheatmap(Heatmap_Matrix, border_color = "gray", color = MYPalette, cellwidth = 10, cellheight = 10, breaks = seq(from=-2,to=2, length.out=200), cluster_cols = TRUE, cluster_rows = FALSE)

ggsave(GSEA_Human_PFC_Heatmap,filename = "../Figures/GSEA_and_DE_Gene_Heatmaps/ILB_vs_HC/ILB_vs_HC_FullIntegrationOSR_GSEA_C2_Top30Pathways_Heatmap.pdf", device = "pdf", height = 18, width = 12, units = "in")

```

```{R}

PathwaysOrder <- as.data.frame(GSEA_Human_PFC_Heatmap$tree_col$labels[GSEA_Human_PFC_Heatmap$tree_col$order])

colnames(PathwaysOrder) <- "Pathways"

Pathway_Table_TOP <- PathwaysOrder

```


##########################################################################################################

Most COMMON differential expressed pathways

```{R}
library(reshape2)
library(dplyr)
library(tidyr)
library(vroom)
library(pheatmap)

#Cell_Type <- gsub("_TREATED_vs_CTRL_GSEA_Sig_Genesets.tsv","",list.files("../Files/Subclusters_GSEA/"))
files <- list.files("../Files/Subclusters_GSEA", full.names = TRUE, pattern = "*_ILB_vs_HC_GSEA_SigBHCorrection_Genesets.tsv")
files <- files[grep("PD_and",files,invert = TRUE)]
GSEA_Aggr_Table <- vroom(files, id = "Cell_Type")
GSEA_Aggr_Table$Cell_Type <- gsub("../Files/Subclusters_GSEA/|_ILB_vs_HC_GSEA_SigBHCorrection_Genesets.tsv","",GSEA_Aggr_Table$Cell_Type)
#GSEA_Aggr_Table$Cell_Type <- #gsub("GLU_Cajal_Retzius","Cajal-Retzius",GSEA_Aggr_Table$Cell_Type)
```



```{R}

GSEA_Aggr_Table_PvalSorted <- GSEA_Aggr_Table[order(GSEA_Aggr_Table$padj),]

PathwayFreq <- as.data.frame(table(GSEA_Aggr_Table$pathway))

PathwayFreq <- PathwayFreq[order(PathwayFreq$Freq, decreasing = TRUE),]

GSEA_Common_Pathways <- as.vector(PathwayFreq$Var1[1:30])

```




```{R}
library(rlist)
Heatmap_Matrix <- list()
for (i in unique(GSEA_Aggr_Table$Cell_Type)) {
  temp_table <- GSEA_Aggr_Table[GSEA_Aggr_Table$Cell_Type %in% i,]
  index <- which(GSEA_Common_Pathways %in% temp_table$pathway)
  if (length(index) == 0) {
    NES_subtable <- as.data.frame(cbind(rep(i,length(GSEA_Common_Pathways)),GSEA_Common_Pathways,rep(0,length(GSEA_Common_Pathways))))
    colnames(NES_subtable) <- c("Cell_Type","pathway","NES")
  }
  else {
    NES_subtable <- temp_table[temp_table$pathway %in% GSEA_Common_Pathways,]
    NES_subtable <- NES_subtable[,c(1,2,7)]
    if (length(NES_subtable$Cell_Type) == 7){
      NES_subtable <- NES_subtable
    }
    else{
      temp_table2 <- as.data.frame(cbind(rep(i,length(GSEA_Common_Pathways[-index])),GSEA_Common_Pathways[-index],rep(0,length(GSEA_Common_Pathways[-index]))))
      colnames(temp_table2) <- c("Cell_Type","pathway","NES")
      NES_subtable <- rbind(NES_subtable,temp_table2)
    }
  }
  Heatmap_Matrix <- list.append(Heatmap_Matrix,NES_subtable)
}

Heatmap_Matrix <- do.call("rbind", Heatmap_Matrix)
```




```{R}
Heatmap_Matrix$NES <- as.numeric(Heatmap_Matrix$NES)
Heatmap_Matrix <- dcast(data = Heatmap_Matrix,formula = Cell_Type~pathway,fun.aggregate = sum,value.var = "NES")
rownames(Heatmap_Matrix) <- Heatmap_Matrix$Cell_Type
Heatmap_Matrix <- Heatmap_Matrix[,-1]


```

doublets: 10,25,28,29

`10` = "GLU_Neurons_6"
`25` = "GABA_Neurons_8"
`28` = "GABA_Neurons_9",
`29` = "GLU_Neurons_12"


```{R}

SubclusterSplitCaseNumbersTable <- read.delim("../Files/Subcluster_SplitCase_NumbersTable.tsv")

Assigned_Clusters <- unique(SubclusterSplitCaseNumbersTable$Var1)

excluded_cells <- Assigned_Clusters[-which(Assigned_Clusters %in% rownames(Heatmap_Matrix))]

#excluded_cells <- gsub("Endothelial_Cells","Endothelial_Cells_and_Microglia",excluded_cells)

#rownames(Heatmap_Matrix) <- gsub("Endothelial_Cells","Endothelial_Cells_and_Microglia",rownames(Heatmap_Matrix))

for (ec in excluded_cells) {
  Heatmap_Matrix <- rbind(Heatmap_Matrix,rep(0,ncol(Heatmap_Matrix)))
  rownames(Heatmap_Matrix)[nrow(Heatmap_Matrix)] <- ec
}

```


```{R}

rownames(Heatmap_Matrix) <- gsub("_"," ",rownames(Heatmap_Matrix))

rownames(Heatmap_Matrix) <- gsub("TEMRA T Cells","Unknown Immune Cells",rownames(Heatmap_Matrix))

rownames(Heatmap_Matrix) <- gsub("Unknown Cluster 66","Unknown Cluster 1",rownames(Heatmap_Matrix))

Cluster_Order <- c("GLU Neurons 1", "GLU Neurons 2", "GLU Neurons 3", "GLU Neurons 4", "GLU Neurons 5", "GLU Neurons 6", "GLU Neurons 7", "GLU Neurons 8", "GLU Neurons 9", "GLU Neurons 10", "GLU Neurons 11", "GLU Neurons 12", "GLU Neurons 13", "GLU Neurons 14", "GLU Neurons 15", "GLU Neurons 16", "GLU Neurons 17", "GLU Neurons 18", "GLU Neurons 19", "GLU Neurons 20", "GABA Neurons 1", "GABA Neurons 2", "GABA Neurons 3", "GABA Neurons 4", "GABA Neurons 5", "GABA Neurons 6", "GABA Neurons 7", "GABA Neurons 8", "GABA Neurons 9", "GABA Neurons 10", "GABA Neurons 11", "GABA Neurons 12", "GABA Neurons 13", "GABA Neurons 14", "GABA Neurons 15", "Astrocytes", "Oligodendrocytes", "OPCs", "Microglia", "Endothelial Cells 1", "Endothelial Cells 2", "Unknown Immune Cells", "Unknown Cluster 1")

Heatmap_Matrix <- Heatmap_Matrix[match(Cluster_Order,rownames(Heatmap_Matrix)),]

```



```{R}
library(ggplot2)

MYPalette <- colorRampPalette(c("magenta","#C228C8","#813384","#000000","#817E3E","#BEB72F","#FFF300"))(200)

pheatmap(Heatmap_Matrix, border_color = "gray", color = MYPalette, cellwidth = 10, cellheight = 10, breaks = seq(from=-2,to=2, length.out=200), cluster_cols = TRUE, cluster_rows = TRUE)

GSEA_Human_PFC_Heatmap <- pheatmap(Heatmap_Matrix, border_color = "gray", color = MYPalette, cellwidth = 10, cellheight = 10, breaks = seq(from=-2,to=2, length.out=200), cluster_cols = TRUE, cluster_rows = FALSE)

ggsave(GSEA_Human_PFC_Heatmap,filename = "../Figures/GSEA_and_DE_Gene_Heatmaps/ILB_vs_HC/ILB_vs_HC_FullIntegrationOSR_GSEA_C2_Top30CommonPathways_Heatmap.pdf", device = "pdf", height = 18, width = 12, units = "in")

```


```{R}
test <- read.delim("../Figures/GSEA_and_DE_Gene_Heatmaps/MostCommonDEPathwaysOrder.tsv", sep = "\t")

PathwaysOrder <- as.data.frame(GSEA_Human_PFC_Heatmap$tree_col$labels[GSEA_Human_PFC_Heatmap$tree_col$order])

colnames(PathwaysOrder) <- "Pathways"

sum(test$Pathways %in% PathwaysOrder$Pathways)

testcontents <- test[test$Pathways %in% PathwaysOrder$Pathways,]

testcontents <- as.data.frame(testcontents)

write.table(testcontents,"../Figures/GSEA_and_DE_Gene_Heatmaps/CommonMostCommonPathwaysbetweenPDandILB.tsv", sep = "\t", quote = FALSE, row.names = FALSE)

Pathway_Table <- PathwaysOrder

Top_exclude <- Pathway_Table_TOP[!(Pathway_Table_TOP$Pathways %in% Pathway_Table$Pathways),]

Top_exclude_df <- as.data.frame(Top_exclude)

colnames(Top_exclude_df) <- "Top Pval Specific Pathways"

Top_common <- Pathway_Table[!(Pathway_Table$Pathways %in% Pathway_Table_TOP$Pathways),]

Top_common_df <- as.data.frame(Top_common)

colnames(Top_common_df) <- "Most Common Specific Pathways"

Unique_pathways_table <- cbind(Top_exclude_df, Top_common_df)

write.table(Unique_pathways_table, file = "../Figures/GSEA_and_DE_Gene_Heatmaps/ILB_vs_HC/ILB_vs_HC_GSEA_AllCells_ExclusivePathwaysTable.tsv", sep = "\t", quote = FALSE, row.names = FALSE)

```


#############################################################################################

Most COMMON differential expressed pathways - Subset for progress report

```{R}
library(reshape2)
library(dplyr)
library(tidyr)
library(vroom)
library(pheatmap)

#Cell_Type <- gsub("_TREATED_vs_CTRL_GSEA_Sig_Genesets.tsv","",list.files("../Files/Subclusters_GSEA/"))
files <- list.files("../Files/Subclusters_GSEA", full.names = TRUE, pattern = "*_ILB_vs_HC_GSEA_SigBHCorrection_Genesets.tsv")
files <- files[grep("PD_and",files,invert = TRUE)]
GSEA_Aggr_Table <- vroom(files, id = "Cell_Type")
GSEA_Aggr_Table$Cell_Type <- gsub("../Files/Subclusters_GSEA/|_ILB_vs_HC_GSEA_SigBHCorrection_Genesets.tsv","",GSEA_Aggr_Table$Cell_Type)
#GSEA_Aggr_Table$Cell_Type <- #gsub("GLU_Cajal_Retzius","Cajal-Retzius",GSEA_Aggr_Table$Cell_Type)
```



```{R}

Pathway_Table <- read.delim("../Figures/GSEA_and_DE_Gene_Heatmaps/MostCommonDEPathwaysOrder.tsv")

Pathway_Table_Subset <- as.data.frame(Pathway_Table[1:11,])

GSEA_Common_Pathways <- as.vector(Pathway_Table_Subset$`Pathway_Table[1:11, ]`)

```




```{R}
library(rlist)
Heatmap_Matrix <- list()
for (i in unique(GSEA_Aggr_Table$Cell_Type)) {
  temp_table <- GSEA_Aggr_Table[GSEA_Aggr_Table$Cell_Type %in% i,]
  index <- which(GSEA_Common_Pathways %in% temp_table$pathway)
  if (length(index) == 0) {
    NES_subtable <- as.data.frame(cbind(rep(i,length(GSEA_Common_Pathways)),GSEA_Common_Pathways,rep(0,length(GSEA_Common_Pathways))))
    colnames(NES_subtable) <- c("Cell_Type","pathway","NES")
  }
  else {
    NES_subtable <- temp_table[temp_table$pathway %in% GSEA_Common_Pathways,]
    NES_subtable <- NES_subtable[,c(1,2,7)]
    if (length(NES_subtable$Cell_Type) == 7){
      NES_subtable <- NES_subtable
    }
    else{
      temp_table2 <- as.data.frame(cbind(rep(i,length(GSEA_Common_Pathways[-index])),GSEA_Common_Pathways[-index],rep(0,length(GSEA_Common_Pathways[-index]))))
      colnames(temp_table2) <- c("Cell_Type","pathway","NES")
      NES_subtable <- rbind(NES_subtable,temp_table2)
    }
  }
  Heatmap_Matrix <- list.append(Heatmap_Matrix,NES_subtable)
}

Heatmap_Matrix <- do.call("rbind", Heatmap_Matrix)
```




```{R}
Heatmap_Matrix$NES <- as.numeric(Heatmap_Matrix$NES)
Heatmap_Matrix <- dcast(data = Heatmap_Matrix,formula = Cell_Type~pathway,fun.aggregate = sum,value.var = "NES")
rownames(Heatmap_Matrix) <- Heatmap_Matrix$Cell_Type
Heatmap_Matrix <- Heatmap_Matrix[,-1]


```

doublets: 10,25,28,29

`10` = "GLU_Neurons_6"
`25` = "GABA_Neurons_8"
`28` = "GABA_Neurons_9",
`29` = "GLU_Neurons_12"


```{R}

SubclusterSplitCaseNumbersTable <- read.delim("../Files/Subcluster_SplitCase_NumbersTable.tsv")

Assigned_Clusters <- unique(SubclusterSplitCaseNumbersTable$Var1)

excluded_cells <- Assigned_Clusters[-which(Assigned_Clusters %in% rownames(Heatmap_Matrix))]

#excluded_cells <- gsub("Endothelial_Cells","Endothelial_Cells_and_Microglia",excluded_cells)

#rownames(Heatmap_Matrix) <- gsub("Endothelial_Cells","Endothelial_Cells_and_Microglia",rownames(Heatmap_Matrix))

for (ec in excluded_cells) {
  Heatmap_Matrix <- rbind(Heatmap_Matrix,rep(0,ncol(Heatmap_Matrix)))
  rownames(Heatmap_Matrix)[nrow(Heatmap_Matrix)] <- ec
}

```


```{R}

Pathway_Table <- read.delim("../Figures/GSEA_and_DE_Gene_Heatmaps/MostCommonDEPathwaysOrder_Subset.tsv")

Pathway_Subset <- Pathway_Table$Pathways

rownames(Heatmap_Matrix) <- gsub("_"," ",rownames(Heatmap_Matrix))

rownames(Heatmap_Matrix) <- gsub("TEMRA T Cells","Unknown Immune Cells",rownames(Heatmap_Matrix))

rownames(Heatmap_Matrix) <- gsub("Unknown Cluster 66","Unknown Cluster 1",rownames(Heatmap_Matrix))

Cluster_Order <- c("GLU Neurons 1", "GLU Neurons 2", "GLU Neurons 3", "GLU Neurons 4", "GLU Neurons 5", "GLU Neurons 6", "GLU Neurons 7", "GLU Neurons 8", "GLU Neurons 9", "GLU Neurons 10", "GLU Neurons 11", "GLU Neurons 12", "GLU Neurons 13", "GLU Neurons 14", "GLU Neurons 15", "GLU Neurons 16", "GLU Neurons 17", "GLU Neurons 18", "GLU Neurons 19", "GLU Neurons 20", "GABA Neurons 1", "GABA Neurons 2", "GABA Neurons 3", "GABA Neurons 4", "GABA Neurons 5", "GABA Neurons 6", "GABA Neurons 7", "GABA Neurons 8", "GABA Neurons 9", "GABA Neurons 10", "GABA Neurons 11", "GABA Neurons 12", "GABA Neurons 13", "GABA Neurons 14", "GABA Neurons 15", "Astrocytes", "Oligodendrocytes", "OPCs", "Microglia", "Endothelial Cells 1", "Endothelial Cells 2", "Unknown Immune Cells", "Unknown Cluster 1")

Heatmap_Matrix <- Heatmap_Matrix[match(Cluster_Order,rownames(Heatmap_Matrix)),]

colnames(Heatmap_Matrix) <- gsub("REACTOME_","",colnames(Heatmap_Matrix))

Heatmap_Matrix <- Heatmap_Matrix[,match(Pathway_Subset,colnames(Heatmap_Matrix))]

Heatmap_Matrix <- Heatmap_Matrix[-(which(rownames(Heatmap_Matrix) %in% "Unknown Cluster 1")),]

```



```{R}
library(ggplot2)

MYPalette <- colorRampPalette(c("magenta","#C228C8","#813384","#000000","#817E3E","#BEB72F","#FFF300"))(200)

pheatmap(Heatmap_Matrix, border_color = "gray", color = MYPalette, cellwidth = 10, cellheight = 10, breaks = seq(from=-2,to=2, length.out=200), cluster_cols = TRUE, cluster_rows = TRUE)

GSEA_Human_PFC_Heatmap <- pheatmap(Heatmap_Matrix, border_color = "gray", color = MYPalette, cellwidth = 10, cellheight = 10, breaks = seq(from=-2,to=2, length.out=200), cluster_cols = FALSE, cluster_rows = FALSE)

ggsave(GSEA_Human_PFC_Heatmap,filename = "../Figures/GSEA_and_DE_Gene_Heatmaps/ILB_vs_HC/ILB_vs_HC_FullIntegrationOSR_GSEA_C2_Top30CommonPathways_Heatmap_GLUPathwaySubset.pdf", device = "pdf", height = 18, width = 8, units = "in")

```


##########################################################################################################

Mitochondrial pathways

```{R}
library(reshape2)
library(dplyr)
library(tidyr)
library(vroom)
library(pheatmap)

#Cell_Type <- gsub("_TREATED_vs_CTRL_GSEA_Sig_Genesets.tsv","",list.files("../Files/Subclusters_GSEA/"))
files <- list.files("../Files/Subclusters_GSEA", full.names = TRUE, pattern = "*_ILB_vs_HC_GSEA_SigBHCorrection_Genesets.tsv")
files <- files[grep("PD_and",files,invert = TRUE)]
GSEA_Aggr_Table <- vroom(files, id = "Cell_Type")
GSEA_Aggr_Table$Cell_Type <- gsub("../Files/Subclusters_GSEA/|_ILB_vs_HC_GSEA_SigBHCorrection_Genesets.tsv","",GSEA_Aggr_Table$Cell_Type)
#GSEA_Aggr_Table$Cell_Type <- #gsub("GLU_Cajal_Retzius","Cajal-Retzius",GSEA_Aggr_Table$Cell_Type)
```


```{R}

GSEA_Aggr_Table_PvalSorted <- GSEA_Aggr_Table[order(GSEA_Aggr_Table$padj),]

```

Expanded_Pathways <- c("BIOCARTA_PGC1A_PATHWAY","KEGG_OXIDATIVE_PHOSPHORYLATION","WP_ELECTRON_TRANSPORT_CHAIN_OXPHOS_SYSTEM_IN_MITOCHONDRIA","REACTOME_RESPIRATORY_ELECTRON_TRANSPORT_ATP_SYNTHESIS_BY_CHEMIOSMOTIC_COUPLING_AND_HEAT_PRODUCTION_BY_UNCOUPLING_PROTEINS","REACTOME_IRON_UPTAKE_AND_TRANSPORT","KEGG_PARKINSONS_DISEASE","WP_MITOCHONDRIAL_CIV_ASSEMBLY","REACTOME_RESPIRATORY_ELECTRON_TRANSPORT","WP_OXIDATIVE_PHOSPHORYLATION","REACTOME_THE_CITRIC_ACID_TCA_CYCLE_AND_RESPIRATORY_ELECTRON_TRANSPORT","REACTOME_MITOCHONDRIAL_PROTEIN_IMPORT","WP_MITOCHONDRIAL_COMPLEX_I_ASSEMBLY_MODEL_OXPHOS_SYSTEM")

Pathways <- c("BIOCARTA_PGC1A_PATHWAY","KEGG_OXIDATIVE_PHOSPHORYLATION","WP_ELECTRON_TRANSPORT_CHAIN_OXPHOS_SYSTEM_IN_MITOCHONDRIA","REACTOME_RESPIRATORY_ELECTRON_TRANSPORT_ATP_SYNTHESIS_BY_CHEMIOSMOTIC_COUPLING_AND_HEAT_PRODUCTION_BY_UNCOUPLING_PROTEINS","REACTOME_IRON_UPTAKE_AND_TRANSPORT")

```{R}

Pathways <- c("BIOCARTA_PGC1A_PATHWAY","KEGG_OXIDATIVE_PHOSPHORYLATION","WP_ELECTRON_TRANSPORT_CHAIN_OXPHOS_SYSTEM_IN_MITOCHONDRIA","REACTOME_RESPIRATORY_ELECTRON_TRANSPORT_ATP_SYNTHESIS_BY_CHEMIOSMOTIC_COUPLING_AND_HEAT_PRODUCTION_BY_UNCOUPLING_PROTEINS","REACTOME_IRON_UPTAKE_AND_TRANSPORT")

```


if (length(index) == 0) {
    NES_subtable <- as.data.frame(rbind(rep(i,length(Pathways),Pathways,rep(0,length(Pathways)))))
    colnames(NES_subtable) <- c("Cell_Type","pathway","NES")
  }
  else {
    NES_subtable <- temp_table[temp_table$pathway %in% Pathways,]
    NES_subtable <- NES_subtable[,c(1,2,7)]
    if (length(NES_subtable$Cell_Type == 8)){
      NES_subtable <- NES_subtable
    }
    else{
      rbind(NES_subtable,as.data.frame(rbind(rep(i,length(Pathways[-index])),Pathways[-index],rep(0,length(Pathways[-index])))))
    }
  }
  Heatmap_Matrix <- cbind(Heatmap_Matrix,NES_subtable)
}

```{R}
library(rlist)
Heatmap_Matrix <- list()
for (i in unique(GSEA_Aggr_Table$Cell_Type)) {
  temp_table <- GSEA_Aggr_Table[GSEA_Aggr_Table$Cell_Type %in% i,]
  index <- which(Pathways %in% temp_table$pathway)
  if (length(index) == 0) {
    NES_subtable <- as.data.frame(cbind(rep(i,length(Pathways)),Pathways,rep(0,length(Pathways))))
    colnames(NES_subtable) <- c("Cell_Type","pathway","NES")
  }
  else {
    NES_subtable <- temp_table[temp_table$pathway %in% Pathways,]
    NES_subtable <- NES_subtable[,c(1,2,7)]
    if (length(NES_subtable$Cell_Type) == 7){
      NES_subtable <- NES_subtable
    }
    else{
      temp_table2 <- as.data.frame(cbind(rep(i,length(Pathways[-index])),Pathways[-index],rep(0,length(Pathways[-index]))))
      colnames(temp_table2) <- c("Cell_Type","pathway","NES")
      NES_subtable <- rbind(NES_subtable,temp_table2)
    }
  }
  Heatmap_Matrix <- list.append(Heatmap_Matrix,NES_subtable)
}

Heatmap_Matrix <- do.call("rbind", Heatmap_Matrix)
```




```{R}
Heatmap_Matrix$NES <- as.numeric(Heatmap_Matrix$NES)
Heatmap_Matrix <- dcast(data = Heatmap_Matrix,formula = Cell_Type~pathway,fun.aggregate = sum,value.var = "NES")
rownames(Heatmap_Matrix) <- Heatmap_Matrix$Cell_Type
Heatmap_Matrix <- Heatmap_Matrix[,-1]


```

doublets: 10,25,28,29

`10` = "GLU_Neurons_6"
`25` = "GABA_Neurons_8"
`28` = "GABA_Neurons_9",
`29` = "GLU_Neurons_12"

```{R}

SubclusterSplitCaseNumbersTable <- read.delim("../Files/Subcluster_SplitCase_NumbersTable.tsv")

Assigned_Clusters <- unique(SubclusterSplitCaseNumbersTable$Var1)

excluded_cells <- Assigned_Clusters[-which(Assigned_Clusters %in% rownames(Heatmap_Matrix))]

#excluded_cells <- gsub("Endothelial_Cells","Endothelial_Cells_and_Microglia",excluded_cells)

#rownames(Heatmap_Matrix) <- gsub("Endothelial_Cells","Endothelial_Cells_and_Microglia",rownames(Heatmap_Matrix))

for (ec in excluded_cells) {
  Heatmap_Matrix <- rbind(Heatmap_Matrix,rep(0,ncol(Heatmap_Matrix)))
  rownames(Heatmap_Matrix)[nrow(Heatmap_Matrix)] <- ec
}

```


```{R}

rownames(Heatmap_Matrix) <- gsub("_"," ",rownames(Heatmap_Matrix))

rownames(Heatmap_Matrix) <- gsub("TEMRA T Cells","Unknown Immune Cells",rownames(Heatmap_Matrix))

rownames(Heatmap_Matrix) <- gsub("Unknown Cluster 66","Unknown Cluster 1",rownames(Heatmap_Matrix))

Cluster_Order <- c("GLU Neurons 1", "GLU Neurons 2", "GLU Neurons 3", "GLU Neurons 4", "GLU Neurons 5", "GLU Neurons 6", "GLU Neurons 7", "GLU Neurons 8", "GLU Neurons 9", "GLU Neurons 10", "GLU Neurons 11", "GLU Neurons 12", "GLU Neurons 13", "GLU Neurons 14", "GLU Neurons 15", "GLU Neurons 16", "GLU Neurons 17", "GLU Neurons 18", "GLU Neurons 19", "GLU Neurons 20", "GABA Neurons 1", "GABA Neurons 2", "GABA Neurons 3", "GABA Neurons 4", "GABA Neurons 5", "GABA Neurons 6", "GABA Neurons 7", "GABA Neurons 8", "GABA Neurons 9", "GABA Neurons 10", "GABA Neurons 11", "GABA Neurons 12", "GABA Neurons 13", "GABA Neurons 14", "GABA Neurons 15", "Astrocytes", "Oligodendrocytes", "OPCs", "Microglia", "Endothelial Cells 1", "Endothelial Cells 2", "Unknown Immune Cells", "Unknown Cluster 1")

Heatmap_Matrix <- Heatmap_Matrix[match(Cluster_Order,rownames(Heatmap_Matrix)),]

```



```{R}
library(ggplot2)

MYPalette <- colorRampPalette(c("magenta","#C228C8","#813384","#000000","#817E3E","#BEB72F","#FFF300"))(200)

pheatmap(Heatmap_Matrix, border_color = "gray", color = MYPalette, cellwidth = 10, cellheight = 10, breaks = seq(from=-2,to=2, length.out=200), cluster_cols = TRUE, cluster_rows = TRUE)

GSEA_Human_PFC_Heatmap <- pheatmap(Heatmap_Matrix, border_color = "gray", color = MYPalette, cellwidth = 10, cellheight = 10, breaks = seq(from=-2,to=2, length.out=200), cluster_cols = FALSE, cluster_rows = FALSE)

ggsave(GSEA_Human_PFC_Heatmap,filename = "../Figures/GSEA_and_DE_Gene_Heatmaps/ILB_vs_HC/ILB_vs_HC_GSEA_C2_Heatmap_MitochondrialPathways.pdf", device = "pdf", height = 18, width = 12, units = "in")

```





######################################################################################################

Unique Pathways

```{R}
library(reshape2)
library(dplyr)
library(tidyr)
library(vroom)
library(pheatmap)

#Cell_Type <- gsub("_TREATED_vs_CTRL_GSEA_Sig_Genesets.tsv","",list.files("../Files/Subclusters_GSEA/"))
files <- list.files("../Files/Subclusters_GSEA", full.names = TRUE, pattern = "*_ILB_vs_HC_GSEA_SigBHCorrection_Genesets.tsv")
files <- files[grep("PD_and",files,invert = TRUE)]
GSEA_Aggr_Table <- vroom(files, id = "Cell_Type")
GSEA_Aggr_Table$Cell_Type <- gsub("../Files/Subclusters_GSEA/|_ILB_vs_HC_GSEA_SigBHCorrection_Genesets.tsv","",GSEA_Aggr_Table$Cell_Type)
#GSEA_Aggr_Table$Cell_Type <- #gsub("GLU_Cajal_Retzius","Cajal-Retzius",GSEA_Aggr_Table$Cell_Type)
```



```{R}

GSEA_Aggr_Table_PvalSorted <- GSEA_Aggr_Table[order(GSEA_Aggr_Table$padj),]

PathwayFreq <- as.data.frame(table(GSEA_Aggr_Table$pathway))

PathwayFreq <- PathwayFreq[order(PathwayFreq$Freq, decreasing = TRUE),]

PathwayFreqUnqiue <- PathwayFreq[PathwayFreq$Freq == 1,]

GSEA_Unique_Pathways <- as.vector(PathwayFreq$Var1)


GSEA_Aggr_Table_PvalSorted_Unique <- GSEA_Aggr_Table_PvalSorted[GSEA_Aggr_Table_PvalSorted$pathway %in% PathwayFreqUnqiue$Var1,]

GSEA_Aggr_Table_PvalSorted_Unique <- GSEA_Aggr_Table_PvalSorted_Unique[order(GSEA_Aggr_Table_PvalSorted_Unique$Cell_Type),]

write.table(GSEA_Aggr_Table_PvalSorted_Unique, file = "../Figures/GSEA_and_DE_Gene_Heatmaps/ILB_vs_HC/ILB_vs_HC_GSEA_Aggr_Table_Unique_Pathways.tsv", sep = "\t", quote = FALSE, row.names = FALSE)

```



######################################################################################################

Looking at pathways per major cell type


```{R}
library(reshape2)
library(dplyr)
library(tidyr)
library(vroom)
library(pheatmap)

#Cell_Type <- gsub("_TREATED_vs_CTRL_GSEA_Sig_Genesets.tsv","",list.files("../Files/Subclusters_GSEA/"))
files <- list.files("../Files/Subclusters_GSEA", full.names = TRUE, pattern = "*_ILB_vs_HC_GSEA_SigBHCorrection_Genesets.tsv")
files <- files[grep("PD_and",files,invert = TRUE)]
GSEA_Aggr_Table <- vroom(files, id = "Cell_Type")
GSEA_Aggr_Table$Cell_Type <- gsub("../Files/Subclusters_GSEA/|_ILB_vs_HC_GSEA_SigBHCorrection_Genesets.tsv","",GSEA_Aggr_Table$Cell_Type)
#GSEA_Aggr_Table$Cell_Type <- #gsub("GLU_Cajal_Retzius","Cajal-Retzius",GSEA_Aggr_Table$Cell_Type)
```

Unique Pathways per MCT?

```{R}
library(dplyr)
library(tidyr)
library(ggplot2)

GSEA_Aggr_Table_MCTAnno <- GSEA_Aggr_Table

GSEA_Aggr_Table_MCTAnno$MCT <- gsub("_[[:digit:]]+","",GSEA_Aggr_Table_MCTAnno$Cell_Type)

UniquePathwaySummaryTable <- group_by(GSEA_Aggr_Table_MCTAnno, MCT) %>% summarise(unique(pathway))

UniquePathwayNumberSummaryTable <- group_by(GSEA_Aggr_Table_MCTAnno, MCT) %>% summarise(length(unique(pathway)))

colnames(UniquePathwayNumberSummaryTable) <- c("Major_Cell_Type", "Number_of_Unique_Significant_Genesets")

UniquePathwayNumberSummaryFigureTable <- UniquePathwayNumberSummaryTable

UniquePathwayNumberSummaryFigureTable$Major_Cell_Type <- gsub("_"," ",UniquePathwayNumberSummaryFigureTable$Major_Cell_Type)

UniquePathwayNumberSummaryFigureTable$Major_Cell_Type <- gsub("TEMRA T Cells","Unknown Immune Cells",UniquePathwayNumberSummaryFigureTable$Major_Cell_Type)

ggplot(UniquePathwayNumberSummaryFigureTable, aes(fill=Major_Cell_Type, y=Number_of_Unique_Significant_Genesets, x=Major_Cell_Type)) + 
    geom_bar(stat="identity") +
  ylab("Unique Significant Genesets") +
  xlab("Major Cell Type") +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1, size = 6),
        axis.text.y = element_text(size = 6),
        legend.position = "none")

UniquePathwayNumberSummaryChart <- ggplot(UniquePathwayNumberSummaryFigureTable, aes(fill=Major_Cell_Type, y=Number_of_Unique_Significant_Genesets, x=Major_Cell_Type)) + 
    geom_bar(stat="identity") +
  ylab("Unique Significant Genesets") +
  xlab("Major Cell Type") +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1, size = 6),
        axis.text.y = element_text(size = 6),
        legend.position = "none")

ggsave(UniquePathwayNumberSummaryChart,filename = paste("../Figures/GSEA_and_DE_Gene_Heatmaps/ILB_vs_HC/ILB_vs_HC_UniquePathwayNumberSummaryChart.pdf",sep = ""), device = "pdf", width = 6, height = 4, units = "in")

```


Correcting number of unique pathways by number of cells (Normalised Pathway Score)

SORT OUT BY SELECTING ONLY FOR CASES IN QUESTION!

```{R}

CellType_SplitCase_NumbersTable <- read.delim("../Files/CellType_SplitCase_NumbersTable.tsv")

CellType_NumbersTable <- group_by(CellType_SplitCase_NumbersTable, Var1) %>% summarise(sum(Freq))

colnames(CellType_NumbersTable) <- c("Major_Cell_Type", "Number_of_Cells")

CellType_NumbersTable <- CellType_NumbersTable[-9,]

PathwayCelltypeNumbers_MergedTable <- merge(UniquePathwayNumberSummaryTable, CellType_NumbersTable)

PathwayCelltypeNumbers_MergedTable$PMC <- (PathwayCelltypeNumbers_MergedTable$Number_of_Unique_Significant_Genesets/PathwayCelltypeNumbers_MergedTable$Number_of_Cells)


PathwayCelltypeNumbers_MergedTable <- PathwayCelltypeNumbers_MergedTable[-8,]

ggplot(PathwayCelltypeNumbers_MergedTable, aes(fill=Major_Cell_Type, y=PMC, x=Major_Cell_Type)) + 
    geom_bar(stat="identity") +
  ylab("Normalised Pathway Score") +
  xlab("Major Cell Type") +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1, size = 6),
        axis.text.y = element_text(size = 6),
        legend.position = "none")

UniquePathwayNormalisedSummaryChart <- ggplot(PathwayCelltypeNumbers_MergedTable, aes(fill=Major_Cell_Type, y=PMC, x=Major_Cell_Type)) + 
    geom_bar(stat="identity") +
  ylab("Normalised Pathway Score") +
  xlab("Major Cell Type") +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1, size = 6),
        axis.text.y = element_text(size = 6),
        legend.position = "none")

ggsave(UniquePathwayNormalisedSummaryChart,filename = paste("../Figures/GSEA_and_DE_Gene_Heatmaps/ILB_vs_HC/ILB_vs_HC_UniquePathwayNormalisedSummaryChart.pdf",sep = ""), device = "pdf", width = 6, height = 4, units = "in")

```


########################################################################################################


Looking at GLU Neurons


```{R}
library(reshape2)
library(dplyr)
library(tidyr)
library(vroom)
library(pheatmap)

#Cell_Type <- gsub("_TREATED_vs_CTRL_GSEA_Sig_Genesets.tsv","",list.files("../Files/Subclusters_GSEA/"))
files <- list.files("../Files/Subclusters_GSEA", full.names = TRUE, pattern = "*_ILB_vs_HC_GSEA_SigBHCorrection_Genesets.tsv")
files <- files[grep("PD_and",files,invert = TRUE)]
GSEA_Aggr_Table <- vroom(files, id = "Cell_Type")
GSEA_Aggr_Table$Cell_Type <- gsub("../Files/Subclusters_GSEA/|_ILB_vs_HC_GSEA_SigBHCorrection_Genesets.tsv","",GSEA_Aggr_Table$Cell_Type)
#GSEA_Aggr_Table$Cell_Type <- #gsub("GLU_Cajal_Retzius","Cajal-Retzius",GSEA_Aggr_Table$Cell_Type)
```


```{R}

GSEA_Aggr_Table <- GSEA_Aggr_Table[grep("GLU_Neurons",GSEA_Aggr_Table$Cell_Type),]

GSEA_Aggr_Table_PvalSorted <- GSEA_Aggr_Table[order(GSEA_Aggr_Table$padj),]

GSEA_Top_Pathways <- unique(GSEA_Aggr_Table_PvalSorted$pathway)[1:15]

```




```{R}
library(rlist)
Heatmap_Matrix <- list()
for (i in unique(GSEA_Aggr_Table$Cell_Type)) {
  temp_table <- GSEA_Aggr_Table[GSEA_Aggr_Table$Cell_Type %in% i,]
  index <- which(GSEA_Top_Pathways %in% temp_table$pathway)
  if (length(index) == 0) {
    NES_subtable <- as.data.frame(cbind(rep(i,length(GSEA_Top_Pathways)),GSEA_Top_Pathways,rep(0,length(GSEA_Top_Pathways))))
    colnames(NES_subtable) <- c("Cell_Type","pathway","NES")
  }
  else {
    NES_subtable <- temp_table[temp_table$pathway %in% GSEA_Top_Pathways,]
    NES_subtable <- NES_subtable[,c(1,2,7)]
    if (length(NES_subtable$Cell_Type) == 7){
      NES_subtable <- NES_subtable
    }
    else{
      temp_table2 <- as.data.frame(cbind(rep(i,length(GSEA_Top_Pathways[-index])),GSEA_Top_Pathways[-index],rep(0,length(GSEA_Top_Pathways[-index]))))
      colnames(temp_table2) <- c("Cell_Type","pathway","NES")
      NES_subtable <- rbind(NES_subtable,temp_table2)
    }
  }
  Heatmap_Matrix <- list.append(Heatmap_Matrix,NES_subtable)
}

Heatmap_Matrix <- do.call("rbind", Heatmap_Matrix)
```




```{R}
Heatmap_Matrix$NES <- as.numeric(Heatmap_Matrix$NES)
Heatmap_Matrix <- dcast(data = Heatmap_Matrix,formula = Cell_Type~pathway,fun.aggregate = sum,value.var = "NES")
rownames(Heatmap_Matrix) <- Heatmap_Matrix$Cell_Type
Heatmap_Matrix <- Heatmap_Matrix[,-1]


```

doublets: 10,25,28,29

`10` = "GLU_Neurons_6"
`25` = "GABA_Neurons_8"
`28` = "GABA_Neurons_9",
`29` = "GLU_Neurons_12"


```{R}

SubclusterSplitCaseNumbersTable <- read.delim("../Files/Subcluster_SplitCase_NumbersTable.tsv")

Assigned_Clusters <- unique(SubclusterSplitCaseNumbersTable$Var1)

excluded_cells <- Assigned_Clusters[-which(Assigned_Clusters %in% rownames(Heatmap_Matrix))]

excluded_cells <- excluded_cells[grep("GLU",excluded_cells)]

#excluded_cells <- gsub("Endothelial_Cells","Endothelial_Cells_and_Microglia",excluded_cells)

#rownames(Heatmap_Matrix) <- gsub("Endothelial_Cells","Endothelial_Cells_and_Microglia",rownames(Heatmap_Matrix))

for (ec in excluded_cells) {
  Heatmap_Matrix <- rbind(Heatmap_Matrix,rep(0,ncol(Heatmap_Matrix)))
  rownames(Heatmap_Matrix)[nrow(Heatmap_Matrix)] <- ec
}

```



```{R}

rownames(Heatmap_Matrix) <- gsub("_"," ",rownames(Heatmap_Matrix))

rownames(Heatmap_Matrix) <- gsub("TEMRA T Cells","Unknown Immune Cells",rownames(Heatmap_Matrix))

rownames(Heatmap_Matrix) <- gsub("Unknown Cluster 66","Unknown Cluster 1",rownames(Heatmap_Matrix))

Cluster_Order <- c("GLU Neurons 1", "GLU Neurons 2", "GLU Neurons 3", "GLU Neurons 4", "GLU Neurons 5", "GLU Neurons 6", "GLU Neurons 7", "GLU Neurons 8", "GLU Neurons 9", "GLU Neurons 10", "GLU Neurons 11", "GLU Neurons 12", "GLU Neurons 13", "GLU Neurons 14", "GLU Neurons 15", "GLU Neurons 16", "GLU Neurons 17", "GLU Neurons 18", "GLU Neurons 19", "GLU Neurons 20")

Heatmap_Matrix <- Heatmap_Matrix[match(Cluster_Order,rownames(Heatmap_Matrix)),]

```

Cluster_Order <- c("GLU Neurons 1", "GLU Neurons 2", "GLU Neurons 3", "GLU Neurons 4", "GLU Neurons 5", "GLU Neurons 6", "GLU Neurons 7", "GLU Neurons 8", "GLU Neurons 9", "GLU Neurons 10", "GLU Neurons 11", "GLU Neurons 12", "GLU Neurons 13", "GLU Neurons 14", "GLU Neurons 15", "GLU Neurons 16", "GLU Neurons 17", "GLU Neurons 18", "GLU Neurons 19", "GLU Neurons 20", "GABA Neurons 1", "GABA Neurons 2", "GABA Neurons 3", "GABA Neurons 4", "GABA Neurons 5", "GABA Neurons 6", "GABA Neurons 7", "GABA Neurons 8", "GABA Neurons 9", "GABA Neurons 10", "GABA Neurons 11", "GABA Neurons 12", "GABA Neurons 13", "GABA Neurons 14", "GABA Neurons 15", "Astrocytes", "Oligodendrocytes", "OPCs", "Microglia", "Endothelial Cells 1", "Endothelial Cells 2", "Unknown Immune Cells", "Unknown Cluster 1")

```{R}
library(ggplot2)

MYPalette <- colorRampPalette(c("magenta","#C228C8","#813384","#000000","#817E3E","#BEB72F","#FFF300"))(200)

pheatmap(Heatmap_Matrix, border_color = "gray", color = MYPalette, cellwidth = 10, cellheight = 10, breaks = seq(from=-2,to=2, length.out=200), cluster_cols = TRUE, cluster_rows = TRUE)

GSEA_Human_PFC_Heatmap <- pheatmap(Heatmap_Matrix, border_color = "gray", color = MYPalette, cellwidth = 10, cellheight = 10, breaks = seq(from=-2,to=2, length.out=200), cluster_cols = TRUE, cluster_rows = FALSE)

ggsave(GSEA_Human_PFC_Heatmap,filename = "../Figures/GSEA_and_DE_Gene_Heatmaps/ILB_vs_HC/ILB_vs_HC_GLU_Neurons_FullIntegrationOSR_GSEA_C2_Top30_Pathways_Heatmap.pdf", device = "pdf", height = 14, width = 12, units = "in")

```

```{R}

PathwaysOrder <- as.data.frame(GSEA_Human_PFC_Heatmap$tree_col$labels[GSEA_Human_PFC_Heatmap$tree_col$order])

colnames(PathwaysOrder) <- "Pathways"

Pathway_Table_TOP <- PathwaysOrder

```


####################################################################################################

GLU Neurons Top 30 MOST COMMON pathways

Looking at GLU Neurons


```{R}
library(reshape2)
library(dplyr)
library(tidyr)
library(vroom)
library(pheatmap)

#Cell_Type <- gsub("_TREATED_vs_CTRL_GSEA_Sig_Genesets.tsv","",list.files("../Files/Subclusters_GSEA/"))
files <- list.files("../Files/Subclusters_GSEA", full.names = TRUE, pattern = "*_ILB_vs_HC_GSEA_SigBHCorrection_Genesets.tsv")
files <- files[grep("PD_and",files,invert = TRUE)]
GSEA_Aggr_Table <- vroom(files, id = "Cell_Type")
GSEA_Aggr_Table$Cell_Type <- gsub("../Files/Subclusters_GSEA/|_ILB_vs_HC_GSEA_SigBHCorrection_Genesets.tsv","",GSEA_Aggr_Table$Cell_Type)
#GSEA_Aggr_Table$Cell_Type <- #gsub("GLU_Cajal_Retzius","Cajal-Retzius",GSEA_Aggr_Table$Cell_Type)
```



```{R}

GSEA_Aggr_Table <- GSEA_Aggr_Table[grep("GLU_Neurons",GSEA_Aggr_Table$Cell_Type),]

GSEA_Aggr_Table_PvalSorted <- GSEA_Aggr_Table[order(GSEA_Aggr_Table$padj),]

PathwayFreq <- as.data.frame(table(GSEA_Aggr_Table$pathway))

PathwayFreq <- PathwayFreq[order(PathwayFreq$Freq, decreasing = TRUE),]

GSEA_Common_Pathways <- as.vector(PathwayFreq$Var1[1:15])

```


```{R}
library(rlist)
Heatmap_Matrix <- list()
for (i in unique(GSEA_Aggr_Table$Cell_Type)) {
  temp_table <- GSEA_Aggr_Table[GSEA_Aggr_Table$Cell_Type %in% i,]
  index <- which(GSEA_Common_Pathways %in% temp_table$pathway)
  if (length(index) == 0) {
    NES_subtable <- as.data.frame(cbind(rep(i,length(GSEA_Common_Pathways)),GSEA_Common_Pathways,rep(0,length(GSEA_Common_Pathways))))
    colnames(NES_subtable) <- c("Cell_Type","pathway","NES")
  }
  else {
    NES_subtable <- temp_table[temp_table$pathway %in% GSEA_Common_Pathways,]
    NES_subtable <- NES_subtable[,c(1,2,7)]
    if (length(NES_subtable$Cell_Type) == 7){
      NES_subtable <- NES_subtable
    }
    else{
      temp_table2 <- as.data.frame(cbind(rep(i,length(GSEA_Common_Pathways[-index])),GSEA_Common_Pathways[-index],rep(0,length(GSEA_Common_Pathways[-index]))))
      colnames(temp_table2) <- c("Cell_Type","pathway","NES")
      NES_subtable <- rbind(NES_subtable,temp_table2)
    }
  }
  Heatmap_Matrix <- list.append(Heatmap_Matrix,NES_subtable)
}

Heatmap_Matrix <- do.call("rbind", Heatmap_Matrix)
```




```{R}
Heatmap_Matrix$NES <- as.numeric(Heatmap_Matrix$NES)
Heatmap_Matrix <- dcast(data = Heatmap_Matrix,formula = Cell_Type~pathway,fun.aggregate = sum,value.var = "NES")
rownames(Heatmap_Matrix) <- Heatmap_Matrix$Cell_Type
Heatmap_Matrix <- Heatmap_Matrix[,-1]


```

doublets: 10,25,28,29

`10` = "GLU_Neurons_6"
`25` = "GABA_Neurons_8"
`28` = "GABA_Neurons_9",
`29` = "GLU_Neurons_12"


```{R}

SubclusterSplitCaseNumbersTable <- read.delim("../Files/Subcluster_SplitCase_NumbersTable.tsv")

Assigned_Clusters <- unique(SubclusterSplitCaseNumbersTable$Var1)

excluded_cells <- Assigned_Clusters[-which(Assigned_Clusters %in% rownames(Heatmap_Matrix))]

excluded_cells <- excluded_cells[grep("GLU",excluded_cells)]

#excluded_cells <- gsub("Endothelial_Cells","Endothelial_Cells_and_Microglia",excluded_cells)

#rownames(Heatmap_Matrix) <- gsub("Endothelial_Cells","Endothelial_Cells_and_Microglia",rownames(Heatmap_Matrix))

for (ec in excluded_cells) {
  Heatmap_Matrix <- rbind(Heatmap_Matrix,rep(0,ncol(Heatmap_Matrix)))
  rownames(Heatmap_Matrix)[nrow(Heatmap_Matrix)] <- ec
}

```



```{R}

rownames(Heatmap_Matrix) <- gsub("_"," ",rownames(Heatmap_Matrix))

rownames(Heatmap_Matrix) <- gsub("TEMRA T Cells","Unknown Immune Cells",rownames(Heatmap_Matrix))

rownames(Heatmap_Matrix) <- gsub("Unknown Cluster 66","Unknown Cluster 1",rownames(Heatmap_Matrix))

Cluster_Order <- c("GLU Neurons 1", "GLU Neurons 2", "GLU Neurons 3", "GLU Neurons 4", "GLU Neurons 5", "GLU Neurons 6", "GLU Neurons 7", "GLU Neurons 8", "GLU Neurons 9", "GLU Neurons 10", "GLU Neurons 11", "GLU Neurons 12", "GLU Neurons 13", "GLU Neurons 14", "GLU Neurons 15", "GLU Neurons 16", "GLU Neurons 17", "GLU Neurons 18", "GLU Neurons 19", "GLU Neurons 20")

Heatmap_Matrix <- Heatmap_Matrix[match(Cluster_Order,rownames(Heatmap_Matrix)),]

```

Cluster_Order <- c("GLU Neurons 1", "GLU Neurons 2", "GLU Neurons 3", "GLU Neurons 4", "GLU Neurons 5", "GLU Neurons 6", "GLU Neurons 7", "GLU Neurons 8", "GLU Neurons 9", "GLU Neurons 10", "GLU Neurons 11", "GLU Neurons 12", "GLU Neurons 13", "GLU Neurons 14", "GLU Neurons 15", "GLU Neurons 16", "GLU Neurons 17", "GLU Neurons 18", "GLU Neurons 19", "GLU Neurons 20", "GABA Neurons 1", "GABA Neurons 2", "GABA Neurons 3", "GABA Neurons 4", "GABA Neurons 5", "GABA Neurons 6", "GABA Neurons 7", "GABA Neurons 8", "GABA Neurons 9", "GABA Neurons 10", "GABA Neurons 11", "GABA Neurons 12", "GABA Neurons 13", "GABA Neurons 14", "GABA Neurons 15", "Astrocytes", "Oligodendrocytes", "OPCs", "Microglia", "Endothelial Cells 1", "Endothelial Cells 2", "Unknown Immune Cells", "Unknown Cluster 1")

```{R}
library(ggplot2)

MYPalette <- colorRampPalette(c("magenta","#C228C8","#813384","#000000","#817E3E","#BEB72F","#FFF300"))(200)

pheatmap(Heatmap_Matrix, border_color = "gray", color = MYPalette, cellwidth = 10, cellheight = 10, breaks = seq(from=-2,to=2, length.out=200), cluster_cols = TRUE, cluster_rows = TRUE)

GSEA_Human_PFC_Heatmap <- pheatmap(Heatmap_Matrix, border_color = "gray", color = MYPalette, cellwidth = 10, cellheight = 10, breaks = seq(from=-2,to=2, length.out=200), cluster_cols = TRUE, cluster_rows = FALSE)

ggsave(GSEA_Human_PFC_Heatmap,filename = "../Figures/GSEA_and_DE_Gene_Heatmaps/ILB_vs_HC/ILB_vs_HC_GLU_Neurons_FullIntegrationOSR_GSEA_C2_MostCommon30_Pathways_Heatmap.pdf", device = "pdf", height = 14, width = 12, units = "in")

```

```{R}

PathwaysOrder <- as.data.frame(GSEA_Human_PFC_Heatmap$tree_col$labels[GSEA_Human_PFC_Heatmap$tree_col$order])

colnames(PathwaysOrder) <- "Pathways"

Pathway_Table <- PathwaysOrder

Top_exclude <- Pathway_Table_TOP[!(Pathway_Table_TOP$Pathways %in% Pathway_Table$Pathways),]

Top_exclude_df <- as.data.frame(Top_exclude)

colnames(Top_exclude_df) <- "Top Pval Specific Pathways"

Top_common <- Pathway_Table[!(Pathway_Table$Pathways %in% Pathway_Table_TOP$Pathways),]

Top_common_df <- as.data.frame(Top_common)

colnames(Top_common_df) <- "Most Common Specific Pathways"

Unique_pathways_table <- cbind(Top_exclude_df, Top_common_df)

write.table(Unique_pathways_table, file = "../Figures/GSEA_and_DE_Gene_Heatmaps/ILB_vs_HC/ILB_vs_HC_GSEA_GLU_Neurons_ExclusivePathwaysTable.tsv", sep = "\t", quote = FALSE, row.names = FALSE)

```


####################################################################################################

Looking at GABA Neurons


```{R}
library(reshape2)
library(dplyr)
library(tidyr)
library(vroom)
library(pheatmap)

#Cell_Type <- gsub("_TREATED_vs_CTRL_GSEA_Sig_Genesets.tsv","",list.files("../Files/Subclusters_GSEA/"))
files <- list.files("../Files/Subclusters_GSEA", full.names = TRUE, pattern = "*_ILB_vs_HC_GSEA_SigBHCorrection_Genesets.tsv")
files <- files[grep("PD_and",files,invert = TRUE)]
GSEA_Aggr_Table <- vroom(files, id = "Cell_Type")
GSEA_Aggr_Table$Cell_Type <- gsub("../Files/Subclusters_GSEA/|_ILB_vs_HC_GSEA_SigBHCorrection_Genesets.tsv","",GSEA_Aggr_Table$Cell_Type)
#GSEA_Aggr_Table$Cell_Type <- #gsub("GLU_Cajal_Retzius","Cajal-Retzius",GSEA_Aggr_Table$Cell_Type)
```


```{R}

GSEA_Aggr_Table <- GSEA_Aggr_Table[grep("GABA_Neurons",GSEA_Aggr_Table$Cell_Type),]

GSEA_Aggr_Table_PvalSorted <- GSEA_Aggr_Table[order(GSEA_Aggr_Table$padj),]

GSEA_Top_Pathways <- unique(GSEA_Aggr_Table_PvalSorted$pathway)[1:15]

```




```{R}
library(rlist)
Heatmap_Matrix <- list()
for (i in unique(GSEA_Aggr_Table$Cell_Type)) {
  temp_table <- GSEA_Aggr_Table[GSEA_Aggr_Table$Cell_Type %in% i,]
  index <- which(GSEA_Top_Pathways %in% temp_table$pathway)
  if (length(index) == 0) {
    NES_subtable <- as.data.frame(cbind(rep(i,length(GSEA_Top_Pathways)),GSEA_Top_Pathways,rep(0,length(GSEA_Top_Pathways))))
    colnames(NES_subtable) <- c("Cell_Type","pathway","NES")
  }
  else {
    NES_subtable <- temp_table[temp_table$pathway %in% GSEA_Top_Pathways,]
    NES_subtable <- NES_subtable[,c(1,2,7)]
    if (length(NES_subtable$Cell_Type) == 7){
      NES_subtable <- NES_subtable
    }
    else{
      temp_table2 <- as.data.frame(cbind(rep(i,length(GSEA_Top_Pathways[-index])),GSEA_Top_Pathways[-index],rep(0,length(GSEA_Top_Pathways[-index]))))
      colnames(temp_table2) <- c("Cell_Type","pathway","NES")
      NES_subtable <- rbind(NES_subtable,temp_table2)
    }
  }
  Heatmap_Matrix <- list.append(Heatmap_Matrix,NES_subtable)
}

Heatmap_Matrix <- do.call("rbind", Heatmap_Matrix)
```




```{R}
Heatmap_Matrix$NES <- as.numeric(Heatmap_Matrix$NES)
Heatmap_Matrix <- dcast(data = Heatmap_Matrix,formula = Cell_Type~pathway,fun.aggregate = sum,value.var = "NES")
rownames(Heatmap_Matrix) <- Heatmap_Matrix$Cell_Type
Heatmap_Matrix <- Heatmap_Matrix[,-1]


```

doublets: 10,25,28,29

`10` = "GLU_Neurons_6"
`25` = "GABA_Neurons_8"
`28` = "GABA_Neurons_9",
`29` = "GLU_Neurons_12"


```{R}

SubclusterSplitCaseNumbersTable <- read.delim("../Files/Subcluster_SplitCase_NumbersTable.tsv")

Assigned_Clusters <- unique(SubclusterSplitCaseNumbersTable$Var1)

excluded_cells <- Assigned_Clusters[-which(Assigned_Clusters %in% rownames(Heatmap_Matrix))]

excluded_cells <- excluded_cells[grep("GABA",excluded_cells)]

#excluded_cells <- gsub("Endothelial_Cells","Endothelial_Cells_and_Microglia",excluded_cells)

#rownames(Heatmap_Matrix) <- gsub("Endothelial_Cells","Endothelial_Cells_and_Microglia",rownames(Heatmap_Matrix))

for (ec in excluded_cells) {
  Heatmap_Matrix <- rbind(Heatmap_Matrix,rep(0,ncol(Heatmap_Matrix)))
  rownames(Heatmap_Matrix)[nrow(Heatmap_Matrix)] <- ec
}

```



```{R}

rownames(Heatmap_Matrix) <- gsub("_"," ",rownames(Heatmap_Matrix))

rownames(Heatmap_Matrix) <- gsub("TEMRA T Cells","Unknown Immune Cells",rownames(Heatmap_Matrix))

rownames(Heatmap_Matrix) <- gsub("Unknown Cluster 66","Unknown Cluster 1",rownames(Heatmap_Matrix))

Cluster_Order <- c("GABA Neurons 1", "GABA Neurons 2", "GABA Neurons 3", "GABA Neurons 4", "GABA Neurons 5", "GABA Neurons 6", "GABA Neurons 7", "GABA Neurons 8", "GABA Neurons 9", "GABA Neurons 10", "GABA Neurons 11", "GABA Neurons 12", "GABA Neurons 13", "GABA Neurons 14", "GABA Neurons 15")

Heatmap_Matrix <- Heatmap_Matrix[match(Cluster_Order,rownames(Heatmap_Matrix)),]

```

Cluster_Order <- c("GLU Neurons 1", "GLU Neurons 2", "GLU Neurons 3", "GLU Neurons 4", "GLU Neurons 5", "GLU Neurons 6", "GLU Neurons 7", "GLU Neurons 8", "GLU Neurons 9", "GLU Neurons 10", "GLU Neurons 11", "GLU Neurons 12", "GLU Neurons 13", "GLU Neurons 14", "GLU Neurons 15", "GLU Neurons 16", "GLU Neurons 17", "GLU Neurons 18", "GLU Neurons 19", "GLU Neurons 20", "GABA Neurons 1", "GABA Neurons 2", "GABA Neurons 3", "GABA Neurons 4", "GABA Neurons 5", "GABA Neurons 6", "GABA Neurons 7", "GABA Neurons 8", "GABA Neurons 9", "GABA Neurons 10", "GABA Neurons 11", "GABA Neurons 12", "GABA Neurons 13", "GABA Neurons 14", "GABA Neurons 15", "Astrocytes", "Oligodendrocytes", "OPCs", "Microglia", "Endothelial Cells 1", "Endothelial Cells 2", "Unknown Immune Cells", "Unknown Cluster 1")

```{R}
library(ggplot2)

MYPalette <- colorRampPalette(c("magenta","#C228C8","#813384","#000000","#817E3E","#BEB72F","#FFF300"))(200)

pheatmap(Heatmap_Matrix, border_color = "gray", color = MYPalette, cellwidth = 10, cellheight = 10, breaks = seq(from=-2,to=2, length.out=200), cluster_cols = TRUE, cluster_rows = TRUE)

GSEA_Human_PFC_Heatmap <- pheatmap(Heatmap_Matrix, border_color = "gray", color = MYPalette, cellwidth = 10, cellheight = 10, breaks = seq(from=-2,to=2, length.out=200), cluster_cols = TRUE, cluster_rows = FALSE)

ggsave(GSEA_Human_PFC_Heatmap,filename = "../Figures/GSEA_and_DE_Gene_Heatmaps/ILB_vs_HC/ILB_vs_HC_GABA_Neurons_FullIntegrationOSR_GSEA_C2_Top30_Pathways_Heatmap.pdf", device = "pdf", height = 14, width = 12, units = "in")

```

```{R}

PathwaysOrder <- as.data.frame(GSEA_Human_PFC_Heatmap$tree_col$labels[GSEA_Human_PFC_Heatmap$tree_col$order])

colnames(PathwaysOrder) <- "Pathways"

Pathway_Table_TOP <- PathwaysOrder

```


####################################################################################################

Gaba Neurons Top 30 MOST COMMON pathways

Looking at GABA Neurons


```{R}
library(reshape2)
library(dplyr)
library(tidyr)
library(vroom)
library(pheatmap)

#Cell_Type <- gsub("_TREATED_vs_CTRL_GSEA_Sig_Genesets.tsv","",list.files("../Files/Subclusters_GSEA/"))
files <- list.files("../Files/Subclusters_GSEA", full.names = TRUE, pattern = "*_ILB_vs_HC_GSEA_SigBHCorrection_Genesets.tsv")
GSEA_Aggr_Table <- vroom(files, id = "Cell_Type")
files <- files[grep("PD_and",files,invert = TRUE)]

GSEA_Aggr_Table$Cell_Type <- gsub("../Files/Subclusters_GSEA/|_ILB_vs_HC_GSEA_SigBHCorrection_Genesets.tsv","",GSEA_Aggr_Table$Cell_Type)
#GSEA_Aggr_Table$Cell_Type <- #gsub("GLU_Cajal_Retzius","Cajal-Retzius",GSEA_Aggr_Table$Cell_Type)
```



```{R}

GSEA_Aggr_Table <- GSEA_Aggr_Table[grep("GABA_Neurons",GSEA_Aggr_Table$Cell_Type),]

GSEA_Aggr_Table_PvalSorted <- GSEA_Aggr_Table[order(GSEA_Aggr_Table$padj),]

PathwayFreq <- as.data.frame(table(GSEA_Aggr_Table$pathway))

PathwayFreq <- PathwayFreq[order(PathwayFreq$Freq, decreasing = TRUE),]

GSEA_Common_Pathways <- as.vector(PathwayFreq$Var1[1:15])

```


```{R}
library(rlist)
Heatmap_Matrix <- list()
for (i in unique(GSEA_Aggr_Table$Cell_Type)) {
  temp_table <- GSEA_Aggr_Table[GSEA_Aggr_Table$Cell_Type %in% i,]
  index <- which(GSEA_Common_Pathways %in% temp_table$pathway)
  if (length(index) == 0) {
    NES_subtable <- as.data.frame(cbind(rep(i,length(GSEA_Common_Pathways)),GSEA_Common_Pathways,rep(0,length(GSEA_Common_Pathways))))
    colnames(NES_subtable) <- c("Cell_Type","pathway","NES")
  }
  else {
    NES_subtable <- temp_table[temp_table$pathway %in% GSEA_Common_Pathways,]
    NES_subtable <- NES_subtable[,c(1,2,7)]
    if (length(NES_subtable$Cell_Type) == 7){
      NES_subtable <- NES_subtable
    }
    else{
      temp_table2 <- as.data.frame(cbind(rep(i,length(GSEA_Common_Pathways[-index])),GSEA_Common_Pathways[-index],rep(0,length(GSEA_Common_Pathways[-index]))))
      colnames(temp_table2) <- c("Cell_Type","pathway","NES")
      NES_subtable <- rbind(NES_subtable,temp_table2)
    }
  }
  Heatmap_Matrix <- list.append(Heatmap_Matrix,NES_subtable)
}

Heatmap_Matrix <- do.call("rbind", Heatmap_Matrix)
```




```{R}
Heatmap_Matrix$NES <- as.numeric(Heatmap_Matrix$NES)
Heatmap_Matrix <- dcast(data = Heatmap_Matrix,formula = Cell_Type~pathway,fun.aggregate = sum,value.var = "NES")
rownames(Heatmap_Matrix) <- Heatmap_Matrix$Cell_Type
Heatmap_Matrix <- Heatmap_Matrix[,-1]


```

doublets: 10,25,28,29

`10` = "GLU_Neurons_6"
`25` = "GABA_Neurons_8"
`28` = "GABA_Neurons_9",
`29` = "GLU_Neurons_12"


```{R}

SubclusterSplitCaseNumbersTable <- read.delim("../Files/Subcluster_SplitCase_NumbersTable.tsv")

Assigned_Clusters <- unique(SubclusterSplitCaseNumbersTable$Var1)

excluded_cells <- Assigned_Clusters[-which(Assigned_Clusters %in% rownames(Heatmap_Matrix))]

excluded_cells <- excluded_cells[grep("GABA",excluded_cells)]

#excluded_cells <- gsub("Endothelial_Cells","Endothelial_Cells_and_Microglia",excluded_cells)

#rownames(Heatmap_Matrix) <- gsub("Endothelial_Cells","Endothelial_Cells_and_Microglia",rownames(Heatmap_Matrix))

for (ec in excluded_cells) {
  Heatmap_Matrix <- rbind(Heatmap_Matrix,rep(0,ncol(Heatmap_Matrix)))
  rownames(Heatmap_Matrix)[nrow(Heatmap_Matrix)] <- ec
}

```



```{R}

rownames(Heatmap_Matrix) <- gsub("_"," ",rownames(Heatmap_Matrix))

rownames(Heatmap_Matrix) <- gsub("TEMRA T Cells","Unknown Immune Cells",rownames(Heatmap_Matrix))

rownames(Heatmap_Matrix) <- gsub("Unknown Cluster 66","Unknown Cluster 1",rownames(Heatmap_Matrix))

Cluster_Order <- c("GABA Neurons 1", "GABA Neurons 2", "GABA Neurons 3", "GABA Neurons 4", "GABA Neurons 5", "GABA Neurons 6", "GABA Neurons 7", "GABA Neurons 8", "GABA Neurons 9", "GABA Neurons 10", "GABA Neurons 11", "GABA Neurons 12", "GABA Neurons 13", "GABA Neurons 14", "GABA Neurons 15")

Heatmap_Matrix <- Heatmap_Matrix[match(Cluster_Order,rownames(Heatmap_Matrix)),]

```

Cluster_Order <- c("GLU Neurons 1", "GLU Neurons 2", "GLU Neurons 3", "GLU Neurons 4", "GLU Neurons 5", "GLU Neurons 6", "GLU Neurons 7", "GLU Neurons 8", "GLU Neurons 9", "GLU Neurons 10", "GLU Neurons 11", "GLU Neurons 12", "GLU Neurons 13", "GLU Neurons 14", "GLU Neurons 15", "GLU Neurons 16", "GLU Neurons 17", "GLU Neurons 18", "GLU Neurons 19", "GLU Neurons 20", "GABA Neurons 1", "GABA Neurons 2", "GABA Neurons 3", "GABA Neurons 4", "GABA Neurons 5", "GABA Neurons 6", "GABA Neurons 7", "GABA Neurons 8", "GABA Neurons 9", "GABA Neurons 10", "GABA Neurons 11", "GABA Neurons 12", "GABA Neurons 13", "GABA Neurons 14", "GABA Neurons 15", "Astrocytes", "Oligodendrocytes", "OPCs", "Microglia", "Endothelial Cells 1", "Endothelial Cells 2", "Unknown Immune Cells", "Unknown Cluster 1")

```{R}
library(ggplot2)

MYPalette <- colorRampPalette(c("magenta","#C228C8","#813384","#000000","#817E3E","#BEB72F","#FFF300"))(200)

pheatmap(Heatmap_Matrix, border_color = "gray", color = MYPalette, cellwidth = 10, cellheight = 10, breaks = seq(from=-2,to=2, length.out=200), cluster_cols = TRUE, cluster_rows = TRUE)

GSEA_Human_PFC_Heatmap <- pheatmap(Heatmap_Matrix, border_color = "gray", color = MYPalette, cellwidth = 10, cellheight = 10, breaks = seq(from=-2,to=2, length.out=200), cluster_cols = TRUE, cluster_rows = FALSE)

ggsave(GSEA_Human_PFC_Heatmap,filename = "../Figures/GSEA_and_DE_Gene_Heatmaps/ILB_vs_HC/ILB_vs_HCGABA_Neurons_FullIntegrationOSR_GSEA_C2_MostCommon30_Pathways_Heatmap.pdf", device = "pdf", height = 14, width = 12, units = "in")

```

```{R}

PathwaysOrder <- as.data.frame(GSEA_Human_PFC_Heatmap$tree_col$labels[GSEA_Human_PFC_Heatmap$tree_col$order])

colnames(PathwaysOrder) <- "Pathways"

Pathway_Table <- PathwaysOrder

Top_exclude <- Pathway_Table_TOP[!(Pathway_Table_TOP$Pathways %in% Pathway_Table$Pathways),]

Top_exclude_df <- as.data.frame(Top_exclude)

colnames(Top_exclude_df) <- "Top Pval Specific Pathways"

Top_common <- Pathway_Table[!(Pathway_Table$Pathways %in% Pathway_Table_TOP$Pathways),]

Top_common_df <- as.data.frame(Top_common)

colnames(Top_common_df) <- "Most Common Specific Pathways"

Unique_pathways_table <- cbind(Top_exclude_df, Top_common_df)

write.table(Unique_pathways_table, file = "../Figures/GSEA_and_DE_Gene_Heatmaps/ILB_vs_HC/ILB_vs_HC_GSEA_GABA_Neurons_ExclusivePathwaysTable.tsv", sep = "\t", quote = FALSE, row.names = FALSE)

```


########################################################################################################

Looking at Glial Cells


```{R}
library(reshape2)
library(dplyr)
library(tidyr)
library(vroom)
library(pheatmap)

#Cell_Type <- gsub("_TREATED_vs_CTRL_GSEA_Sig_Genesets.tsv","",list.files("../Files/Subclusters_GSEA/"))
files <- list.files("../Files/Subclusters_GSEA", full.names = TRUE, pattern = "*_ILB_vs_HC_GSEA_SigBHCorrection_Genesets.tsv")
files <- files[grep("PD_and",files,invert = TRUE)]
GSEA_Aggr_Table <- vroom(files, id = "Cell_Type")
GSEA_Aggr_Table$Cell_Type <- gsub("../Files/Subclusters_GSEA/|_ILB_vs_HC_GSEA_SigBHCorrection_Genesets.tsv","",GSEA_Aggr_Table$Cell_Type)
#GSEA_Aggr_Table$Cell_Type <- #gsub("GLU_Cajal_Retzius","Cajal-Retzius",GSEA_Aggr_Table$Cell_Type)
```


```{R}

GSEA_Aggr_Table <- GSEA_Aggr_Table[grep("_Neurons",GSEA_Aggr_Table$Cell_Type, invert = TRUE),]

GSEA_Aggr_Table_PvalSorted <- GSEA_Aggr_Table[order(GSEA_Aggr_Table$padj),]

GSEA_Top_Pathways <- unique(GSEA_Aggr_Table_PvalSorted$pathway)

```




```{R}
library(rlist)
Heatmap_Matrix <- list()
for (i in unique(GSEA_Aggr_Table$Cell_Type)) {
  temp_table <- GSEA_Aggr_Table[GSEA_Aggr_Table$Cell_Type %in% i,]
  index <- which(GSEA_Top_Pathways %in% temp_table$pathway)
  if (length(index) == 0) {
    NES_subtable <- as.data.frame(cbind(rep(i,length(GSEA_Top_Pathways)),GSEA_Top_Pathways,rep(0,length(GSEA_Top_Pathways))))
    colnames(NES_subtable) <- c("Cell_Type","pathway","NES")
  }
  else {
    NES_subtable <- temp_table[temp_table$pathway %in% GSEA_Top_Pathways,]
    NES_subtable <- NES_subtable[,c(1,2,7)]
    if (length(NES_subtable$Cell_Type) == 7){
      NES_subtable <- NES_subtable
    }
    else{
      temp_table2 <- as.data.frame(cbind(rep(i,length(GSEA_Top_Pathways[-index])),GSEA_Top_Pathways[-index],rep(0,length(GSEA_Top_Pathways[-index]))))
      colnames(temp_table2) <- c("Cell_Type","pathway","NES")
      NES_subtable <- rbind(NES_subtable,temp_table2)
    }
  }
  Heatmap_Matrix <- list.append(Heatmap_Matrix,NES_subtable)
}

Heatmap_Matrix <- do.call("rbind", Heatmap_Matrix)
```




```{R}
Heatmap_Matrix$NES <- as.numeric(Heatmap_Matrix$NES)
Heatmap_Matrix <- dcast(data = Heatmap_Matrix,formula = Cell_Type~pathway,fun.aggregate = sum,value.var = "NES")
rownames(Heatmap_Matrix) <- Heatmap_Matrix$Cell_Type
Heatmap_Matrix <- Heatmap_Matrix[,-1]


```

doublets: 10,25,28,29

`10` = "GLU_Neurons_6"
`25` = "GABA_Neurons_8"
`28` = "GABA_Neurons_9",
`29` = "GLU_Neurons_12"


```{R}

SubclusterSplitCaseNumbersTable <- read.delim("../Files/Subcluster_SplitCase_NumbersTable.tsv")

Assigned_Clusters <- unique(SubclusterSplitCaseNumbersTable$Var1)

excluded_cells <- Assigned_Clusters[-which(Assigned_Clusters %in% rownames(Heatmap_Matrix))]

excluded_cells <- excluded_cells[grep("Neuron",excluded_cells, invert = TRUE)]

#excluded_cells <- gsub("Endothelial_Cells","Endothelial_Cells_and_Microglia",excluded_cells)

#rownames(Heatmap_Matrix) <- gsub("Endothelial_Cells","Endothelial_Cells_and_Microglia",rownames(Heatmap_Matrix))

for (ec in excluded_cells) {
  Heatmap_Matrix <- rbind(Heatmap_Matrix,rep(0,ncol(Heatmap_Matrix)))
  rownames(Heatmap_Matrix)[nrow(Heatmap_Matrix)] <- ec
}

```



```{R}

rownames(Heatmap_Matrix) <- gsub("_"," ",rownames(Heatmap_Matrix))

rownames(Heatmap_Matrix) <- gsub("TEMRA T Cells","Unknown Immune Cells",rownames(Heatmap_Matrix))

rownames(Heatmap_Matrix) <- gsub("Unknown Cluster 66","Unknown Cluster 1",rownames(Heatmap_Matrix))

Cluster_Order <- c("Astrocytes", "Oligodendrocytes", "OPCs", "Microglia", "Endothelial Cells 1", "Endothelial Cells 2", "Unknown Immune Cells", "Unknown Cluster 1")

Heatmap_Matrix <- Heatmap_Matrix[match(Cluster_Order,rownames(Heatmap_Matrix)),]

```

Cluster_Order <- c("GLU Neurons 1", "GLU Neurons 2", "GLU Neurons 3", "GLU Neurons 4", "GLU Neurons 5", "GLU Neurons 6", "GLU Neurons 7", "GLU Neurons 8", "GLU Neurons 9", "GLU Neurons 10", "GLU Neurons 11", "GLU Neurons 12", "GLU Neurons 13", "GLU Neurons 14", "GLU Neurons 15", "GLU Neurons 16", "GLU Neurons 17", "GLU Neurons 18", "GLU Neurons 19", "GLU Neurons 20", "GABA Neurons 1", "GABA Neurons 2", "GABA Neurons 3", "GABA Neurons 4", "GABA Neurons 5", "GABA Neurons 6", "GABA Neurons 7", "GABA Neurons 8", "GABA Neurons 9", "GABA Neurons 10", "GABA Neurons 11", "GABA Neurons 12", "GABA Neurons 13", "GABA Neurons 14", "GABA Neurons 15", "Astrocytes", "Oligodendrocytes", "OPCs", "Microglia", "Endothelial Cells 1", "Endothelial Cells 2", "Unknown Immune Cells", "Unknown Cluster 1")

```{R}
library(ggplot2)

MYPalette <- colorRampPalette(c("magenta","#C228C8","#813384","#000000","#817E3E","#BEB72F","#FFF300"))(200)

pheatmap(Heatmap_Matrix, border_color = "gray", color = MYPalette, cellwidth = 10, cellheight = 10, breaks = seq(from=-2,to=2, length.out=200), cluster_cols = TRUE, cluster_rows = TRUE)

GSEA_Human_PFC_Heatmap <- pheatmap(Heatmap_Matrix, border_color = "gray", color = MYPalette, cellwidth = 10, cellheight = 10, breaks = seq(from=-2,to=2, length.out=200), cluster_cols = TRUE, cluster_rows = FALSE)

ggsave(GSEA_Human_PFC_Heatmap,filename = "../Figures/GSEA_and_DE_Gene_Heatmaps/ILB_vs_HC/ILB_vs_HC_GlialCells_FullIntegrationOSR_GSEA_C2_Top30_Pathways_Heatmap.pdf", device = "pdf", height = 10, width = 12, units = "in")

```

```{R}

PathwaysOrder <- as.data.frame(GSEA_Human_PFC_Heatmap$tree_col$labels[GSEA_Human_PFC_Heatmap$tree_col$order])

colnames(PathwaysOrder) <- "Pathways"

Pathway_Table_TOP <- PathwaysOrder

```


####################################################################################################

Glial Cells Top 30 MOST COMMON pathways



```{R}
library(reshape2)
library(dplyr)
library(tidyr)
library(vroom)
library(pheatmap)

#Cell_Type <- gsub("_TREATED_vs_CTRL_GSEA_Sig_Genesets.tsv","",list.files("../Files/Subclusters_GSEA/"))
files <- list.files("../Files/Subclusters_GSEA", full.names = TRUE, pattern = "*_ILB_vs_HC_GSEA_SigBHCorrection_Genesets.tsv")
files <- files[grep("PD_and",files,invert = TRUE)]
GSEA_Aggr_Table <- vroom(files, id = "Cell_Type")
GSEA_Aggr_Table$Cell_Type <- gsub("../Files/Subclusters_GSEA/|_ILB_vs_HC_GSEA_SigBHCorrection_Genesets.tsv","",GSEA_Aggr_Table$Cell_Type)
#GSEA_Aggr_Table$Cell_Type <- #gsub("GLU_Cajal_Retzius","Cajal-Retzius",GSEA_Aggr_Table$Cell_Type)
```



```{R}

GSEA_Aggr_Table <- GSEA_Aggr_Table[grep("_Neurons",GSEA_Aggr_Table$Cell_Type, invert = TRUE),]

GSEA_Aggr_Table_PvalSorted <- GSEA_Aggr_Table[order(GSEA_Aggr_Table$padj),]

PathwayFreq <- as.data.frame(table(GSEA_Aggr_Table$pathway))

PathwayFreq <- PathwayFreq[order(PathwayFreq$Freq, decreasing = TRUE),]

GSEA_Common_Pathways <- as.vector(PathwayFreq$Var1)

```


```{R}
library(rlist)
Heatmap_Matrix <- list()
for (i in unique(GSEA_Aggr_Table$Cell_Type)) {
  temp_table <- GSEA_Aggr_Table[GSEA_Aggr_Table$Cell_Type %in% i,]
  index <- which(GSEA_Common_Pathways %in% temp_table$pathway)
  if (length(index) == 0) {
    NES_subtable <- as.data.frame(cbind(rep(i,length(GSEA_Common_Pathways)),GSEA_Common_Pathways,rep(0,length(GSEA_Common_Pathways))))
    colnames(NES_subtable) <- c("Cell_Type","pathway","NES")
  }
  else {
    NES_subtable <- temp_table[temp_table$pathway %in% GSEA_Common_Pathways,]
    NES_subtable <- NES_subtable[,c(1,2,7)]
    if (length(NES_subtable$Cell_Type) == 7){
      NES_subtable <- NES_subtable
    }
    else{
      temp_table2 <- as.data.frame(cbind(rep(i,length(GSEA_Common_Pathways[-index])),GSEA_Common_Pathways[-index],rep(0,length(GSEA_Common_Pathways[-index]))))
      colnames(temp_table2) <- c("Cell_Type","pathway","NES")
      NES_subtable <- rbind(NES_subtable,temp_table2)
    }
  }
  Heatmap_Matrix <- list.append(Heatmap_Matrix,NES_subtable)
}

Heatmap_Matrix <- do.call("rbind", Heatmap_Matrix)
```




```{R}
Heatmap_Matrix$NES <- as.numeric(Heatmap_Matrix$NES)
Heatmap_Matrix <- dcast(data = Heatmap_Matrix,formula = Cell_Type~pathway,fun.aggregate = sum,value.var = "NES")
rownames(Heatmap_Matrix) <- Heatmap_Matrix$Cell_Type
Heatmap_Matrix <- Heatmap_Matrix[,-1]


```

doublets: 10,25,28,29

`10` = "GLU_Neurons_6"
`25` = "GABA_Neurons_8"
`28` = "GABA_Neurons_9",
`29` = "GLU_Neurons_12"


```{R}

SubclusterSplitCaseNumbersTable <- read.delim("../Files/Subcluster_SplitCase_NumbersTable.tsv")

Assigned_Clusters <- unique(SubclusterSplitCaseNumbersTable$Var1)

excluded_cells <- Assigned_Clusters[-which(Assigned_Clusters %in% rownames(Heatmap_Matrix))]

excluded_cells <- excluded_cells[grep("Neuron",excluded_cells, invert = TRUE)]

#excluded_cells <- gsub("Endothelial_Cells","Endothelial_Cells_and_Microglia",excluded_cells)

#rownames(Heatmap_Matrix) <- gsub("Endothelial_Cells","Endothelial_Cells_and_Microglia",rownames(Heatmap_Matrix))

for (ec in excluded_cells) {
  Heatmap_Matrix <- rbind(Heatmap_Matrix,rep(0,ncol(Heatmap_Matrix)))
  rownames(Heatmap_Matrix)[nrow(Heatmap_Matrix)] <- ec
}

```



```{R}

rownames(Heatmap_Matrix) <- gsub("_"," ",rownames(Heatmap_Matrix))

rownames(Heatmap_Matrix) <- gsub("TEMRA T Cells","Unknown Immune Cells",rownames(Heatmap_Matrix))

rownames(Heatmap_Matrix) <- gsub("Unknown Cluster 66","Unknown Cluster 1",rownames(Heatmap_Matrix))

Cluster_Order <- c("Astrocytes", "Oligodendrocytes", "OPCs", "Microglia", "Endothelial Cells 1", "Endothelial Cells 2", "Unknown Immune Cells", "Unknown Cluster 1")

Heatmap_Matrix <- Heatmap_Matrix[match(Cluster_Order,rownames(Heatmap_Matrix)),]

```

Cluster_Order <- c("GLU Neurons 1", "GLU Neurons 2", "GLU Neurons 3", "GLU Neurons 4", "GLU Neurons 5", "GLU Neurons 6", "GLU Neurons 7", "GLU Neurons 8", "GLU Neurons 9", "GLU Neurons 10", "GLU Neurons 11", "GLU Neurons 12", "GLU Neurons 13", "GLU Neurons 14", "GLU Neurons 15", "GLU Neurons 16", "GLU Neurons 17", "GLU Neurons 18", "GLU Neurons 19", "GLU Neurons 20", "GABA Neurons 1", "GABA Neurons 2", "GABA Neurons 3", "GABA Neurons 4", "GABA Neurons 5", "GABA Neurons 6", "GABA Neurons 7", "GABA Neurons 8", "GABA Neurons 9", "GABA Neurons 10", "GABA Neurons 11", "GABA Neurons 12", "GABA Neurons 13", "GABA Neurons 14", "GABA Neurons 15", "Astrocytes", "Oligodendrocytes", "OPCs", "Microglia", "Endothelial Cells 1", "Endothelial Cells 2", "Unknown Immune Cells", "Unknown Cluster 1")

```{R}
library(ggplot2)

MYPalette <- colorRampPalette(c("magenta","#C228C8","#813384","#000000","#817E3E","#BEB72F","#FFF300"))(200)

pheatmap(Heatmap_Matrix, border_color = "gray", color = MYPalette, cellwidth = 10, cellheight = 10, breaks = seq(from=-2,to=2, length.out=200), cluster_cols = TRUE, cluster_rows = TRUE)

GSEA_Human_PFC_Heatmap <- pheatmap(Heatmap_Matrix, border_color = "gray", color = MYPalette, cellwidth = 10, cellheight = 10, breaks = seq(from=-2,to=2, length.out=200), cluster_cols = TRUE, cluster_rows = FALSE)

ggsave(GSEA_Human_PFC_Heatmap,filename = "../Figures/GSEA_and_DE_Gene_Heatmaps/ILB_vs_HC/ILB_vs_HC_GlialCells_FullIntegrationOSR_GSEA_C2_MostCommon30_Pathways_Heatmap.pdf", device = "pdf", height = 14, width = 12, units = "in")

```


```{R}

PathwaysOrder <- as.data.frame(GSEA_Human_PFC_Heatmap$tree_col$labels[GSEA_Human_PFC_Heatmap$tree_col$order])

colnames(PathwaysOrder) <- "Pathways"

Pathway_Table <- PathwaysOrder

Top_exclude <- Pathway_Table_TOP[!(Pathway_Table_TOP$Pathways %in% Pathway_Table$Pathways),]

Top_exclude_df <- as.data.frame(Top_exclude)

colnames(Top_exclude_df) <- "Top Pval Specific Pathways"

Top_common <- Pathway_Table[!(Pathway_Table$Pathways %in% Pathway_Table_TOP$Pathways),]

Top_common_df <- as.data.frame(Top_common)

colnames(Top_common_df) <- "Most Common Specific Pathways"

Unique_pathways_table <- cbind(Top_exclude_df, Top_common_df)

write.table(Unique_pathways_table, file = "../Figures/GSEA_and_DE_Gene_Heatmaps/ILB_vs_HC/ILB_vs_HC_GSEA_GlialCells_ExclusivePathwaysTable.tsv", sep = "\t", quote = FALSE, row.names = FALSE)

```


###################################################################################################

For 30 top DE genes in PD vs HC

```{R}
library(reshape2)
library(dplyr)
library(tidyr)
library(vroom)
library(pheatmap)

#Cell_Type <- gsub("_TREATED_vs_CTRL_GSEA_Sig_Genesets.tsv","",list.files("../Files/Subclusters_GSEA/"))
files <- list.files("../Files/Subclusters_GSEA", full.names = TRUE, pattern = "*_ILB_vs_HC_GSEA_SigBHCorrection_Genesets.tsv")
files <- files[grep("PD_and",files,invert = TRUE)]
GSEA_Aggr_Table <- vroom(files, id = "Cell_Type")
GSEA_Aggr_Table$Cell_Type <- gsub("../Files/Subclusters_GSEA/|_ILB_vs_HC_GSEA_SigBHCorrection_Genesets.tsv","",GSEA_Aggr_Table$Cell_Type)
#GSEA_Aggr_Table$Cell_Type <- #gsub("GLU_Cajal_Retzius","Cajal-Retzius",GSEA_Aggr_Table$Cell_Type)
```



```{R}

GSEA_Aggr_Table_PvalSorted <- GSEA_Aggr_Table[order(GSEA_Aggr_Table$padj),]

PD_vs_HC_Top_Pathways <- read.delim("../Figures/GSEA_and_DE_Gene_Heatmaps/MostDEPathwaysOrder.tsv", sep = "\t")

GSEA_Top_Pathways <- unique(PD_vs_HC_Top_Pathways$Pathways)

```




```{R}
library(rlist)
Heatmap_Matrix <- list()
for (i in unique(GSEA_Aggr_Table$Cell_Type)) {
  temp_table <- GSEA_Aggr_Table[GSEA_Aggr_Table$Cell_Type %in% i,]
  index <- which(GSEA_Top_Pathways %in% temp_table$pathway)
  if (length(index) == 0) {
    NES_subtable <- as.data.frame(cbind(rep(i,length(GSEA_Top_Pathways)),GSEA_Top_Pathways,rep(0,length(GSEA_Top_Pathways))))
    colnames(NES_subtable) <- c("Cell_Type","pathway","NES")
  }
  else {
    NES_subtable <- temp_table[temp_table$pathway %in% GSEA_Top_Pathways,]
    NES_subtable <- NES_subtable[,c(1,2,7)]
    if (length(NES_subtable$Cell_Type) == 7){
      NES_subtable <- NES_subtable
    }
    else{
      temp_table2 <- as.data.frame(cbind(rep(i,length(GSEA_Top_Pathways[-index])),GSEA_Top_Pathways[-index],rep(0,length(GSEA_Top_Pathways[-index]))))
      colnames(temp_table2) <- c("Cell_Type","pathway","NES")
      NES_subtable <- rbind(NES_subtable,temp_table2)
    }
  }
  Heatmap_Matrix <- list.append(Heatmap_Matrix,NES_subtable)
}

Heatmap_Matrix <- do.call("rbind", Heatmap_Matrix)
```




```{R}
Heatmap_Matrix$NES <- as.numeric(Heatmap_Matrix$NES)
Heatmap_Matrix <- dcast(data = Heatmap_Matrix,formula = Cell_Type~pathway,fun.aggregate = sum,value.var = "NES")
rownames(Heatmap_Matrix) <- Heatmap_Matrix$Cell_Type
Heatmap_Matrix <- Heatmap_Matrix[,-1]


```

doublets: 10,25,28,29

`10` = "GLU_Neurons_6"
`25` = "GABA_Neurons_8"
`28` = "GABA_Neurons_9",
`29` = "GLU_Neurons_12"


```{R}

SubclusterSplitCaseNumbersTable <- read.delim("../Files/Subcluster_SplitCase_NumbersTable.tsv")

Assigned_Clusters <- unique(SubclusterSplitCaseNumbersTable$Var1)

excluded_cells <- Assigned_Clusters[-which(Assigned_Clusters %in% rownames(Heatmap_Matrix))]

#excluded_cells <- gsub("Endothelial_Cells","Endothelial_Cells_and_Microglia",excluded_cells)

#rownames(Heatmap_Matrix) <- gsub("Endothelial_Cells","Endothelial_Cells_and_Microglia",rownames(Heatmap_Matrix))

for (ec in excluded_cells) {
  Heatmap_Matrix <- rbind(Heatmap_Matrix,rep(0,ncol(Heatmap_Matrix)))
  rownames(Heatmap_Matrix)[nrow(Heatmap_Matrix)] <- ec
}

```


```{R}

rownames(Heatmap_Matrix) <- gsub("_"," ",rownames(Heatmap_Matrix))

rownames(Heatmap_Matrix) <- gsub("TEMRA T Cells","Unknown Immune Cells",rownames(Heatmap_Matrix))

rownames(Heatmap_Matrix) <- gsub("Unknown Cluster 66","Unknown Cluster 1",rownames(Heatmap_Matrix))

Cluster_Order <- c("GLU Neurons 1", "GLU Neurons 2", "GLU Neurons 3", "GLU Neurons 4", "GLU Neurons 5", "GLU Neurons 6", "GLU Neurons 7", "GLU Neurons 8", "GLU Neurons 9", "GLU Neurons 10", "GLU Neurons 11", "GLU Neurons 12", "GLU Neurons 13", "GLU Neurons 14", "GLU Neurons 15", "GLU Neurons 16", "GLU Neurons 17", "GLU Neurons 18", "GLU Neurons 19", "GLU Neurons 20", "GABA Neurons 1", "GABA Neurons 2", "GABA Neurons 3", "GABA Neurons 4", "GABA Neurons 5", "GABA Neurons 6", "GABA Neurons 7", "GABA Neurons 8", "GABA Neurons 9", "GABA Neurons 10", "GABA Neurons 11", "GABA Neurons 12", "GABA Neurons 13", "GABA Neurons 14", "GABA Neurons 15", "Astrocytes", "Oligodendrocytes", "OPCs", "Microglia", "Endothelial Cells 1", "Endothelial Cells 2", "Unknown Immune Cells", "Unknown Cluster 1")

Heatmap_Matrix <- Heatmap_Matrix[match(Cluster_Order,rownames(Heatmap_Matrix)),]

Heatmap_Matrix <- Heatmap_Matrix[,match(GSEA_Top_Pathways,colnames(Heatmap_Matrix))]

```



```{R}
library(ggplot2)

MYPalette <- colorRampPalette(c("magenta","#C228C8","#813384","#000000","#817E3E","#BEB72F","#FFF300"))(200)

pheatmap(Heatmap_Matrix, border_color = "gray", color = MYPalette, cellwidth = 10, cellheight = 10, breaks = seq(from=-2,to=2, length.out=200), cluster_cols = TRUE, cluster_rows = TRUE)

GSEA_Human_PFC_Heatmap <- pheatmap(Heatmap_Matrix, border_color = "gray", color = MYPalette, cellwidth = 10, cellheight = 10, breaks = seq(from=-2,to=2, length.out=200), cluster_cols = FALSE, cluster_rows = FALSE)

ggsave(GSEA_Human_PFC_Heatmap,filename = "../Figures/GSEA_and_DE_Gene_Heatmaps/ILB_vs_HC/ILB_vs_HC_FullIntegrationOSR_GSEA_C2_Top30PathwaysinPDvsHC_Heatmap.pdf", device = "pdf", height = 18, width = 12, units = "in")

```

####################################################################################################

For 30 top most common DE genes in PD vs HC

```{R}
library(reshape2)
library(dplyr)
library(tidyr)
library(vroom)
library(pheatmap)

#Cell_Type <- gsub("_TREATED_vs_CTRL_GSEA_Sig_Genesets.tsv","",list.files("../Files/Subclusters_GSEA/"))
files <- list.files("../Files/Subclusters_GSEA", full.names = TRUE, pattern = "*_ILB_vs_HC_GSEA_SigBHCorrection_Genesets.tsv")
files <- files[grep("PD_and",files,invert = TRUE)]
GSEA_Aggr_Table <- vroom(files, id = "Cell_Type")
GSEA_Aggr_Table$Cell_Type <- gsub("../Files/Subclusters_GSEA/|_ILB_vs_HC_GSEA_SigBHCorrection_Genesets.tsv","",GSEA_Aggr_Table$Cell_Type)
#GSEA_Aggr_Table$Cell_Type <- #gsub("GLU_Cajal_Retzius","Cajal-Retzius",GSEA_Aggr_Table$Cell_Type)
```



```{R}

GSEA_Aggr_Table_PvalSorted <- GSEA_Aggr_Table[order(GSEA_Aggr_Table$padj),]

PD_vs_HC_Top_Pathways <- read.delim("../Figures/GSEA_and_DE_Gene_Heatmaps/MostCommonDEPathwaysOrder.tsv", sep = "\t")

GSEA_Top_Pathways <- unique(PD_vs_HC_Top_Pathways$Pathways)

```




```{R}
library(rlist)
Heatmap_Matrix <- list()
for (i in unique(GSEA_Aggr_Table$Cell_Type)) {
  temp_table <- GSEA_Aggr_Table[GSEA_Aggr_Table$Cell_Type %in% i,]
  index <- which(GSEA_Top_Pathways %in% temp_table$pathway)
  if (length(index) == 0) {
    NES_subtable <- as.data.frame(cbind(rep(i,length(GSEA_Top_Pathways)),GSEA_Top_Pathways,rep(0,length(GSEA_Top_Pathways))))
    colnames(NES_subtable) <- c("Cell_Type","pathway","NES")
  }
  else {
    NES_subtable <- temp_table[temp_table$pathway %in% GSEA_Top_Pathways,]
    NES_subtable <- NES_subtable[,c(1,2,7)]
    if (length(NES_subtable$Cell_Type) == 7){
      NES_subtable <- NES_subtable
    }
    else{
      temp_table2 <- as.data.frame(cbind(rep(i,length(GSEA_Top_Pathways[-index])),GSEA_Top_Pathways[-index],rep(0,length(GSEA_Top_Pathways[-index]))))
      colnames(temp_table2) <- c("Cell_Type","pathway","NES")
      NES_subtable <- rbind(NES_subtable,temp_table2)
    }
  }
  Heatmap_Matrix <- list.append(Heatmap_Matrix,NES_subtable)
}

Heatmap_Matrix <- do.call("rbind", Heatmap_Matrix)
```




```{R}
Heatmap_Matrix$NES <- as.numeric(Heatmap_Matrix$NES)
Heatmap_Matrix <- dcast(data = Heatmap_Matrix,formula = Cell_Type~pathway,fun.aggregate = sum,value.var = "NES")
rownames(Heatmap_Matrix) <- Heatmap_Matrix$Cell_Type
Heatmap_Matrix <- Heatmap_Matrix[,-1]


```

doublets: 10,25,28,29

`10` = "GLU_Neurons_6"
`25` = "GABA_Neurons_8"
`28` = "GABA_Neurons_9",
`29` = "GLU_Neurons_12"


```{R}

SubclusterSplitCaseNumbersTable <- read.delim("../Files/Subcluster_SplitCase_NumbersTable.tsv")

Assigned_Clusters <- unique(SubclusterSplitCaseNumbersTable$Var1)

excluded_cells <- Assigned_Clusters[-which(Assigned_Clusters %in% rownames(Heatmap_Matrix))]

#excluded_cells <- gsub("Endothelial_Cells","Endothelial_Cells_and_Microglia",excluded_cells)

#rownames(Heatmap_Matrix) <- gsub("Endothelial_Cells","Endothelial_Cells_and_Microglia",rownames(Heatmap_Matrix))

for (ec in excluded_cells) {
  Heatmap_Matrix <- rbind(Heatmap_Matrix,rep(0,ncol(Heatmap_Matrix)))
  rownames(Heatmap_Matrix)[nrow(Heatmap_Matrix)] <- ec
}

```


```{R}

rownames(Heatmap_Matrix) <- gsub("_"," ",rownames(Heatmap_Matrix))

rownames(Heatmap_Matrix) <- gsub("TEMRA T Cells","Unknown Immune Cells",rownames(Heatmap_Matrix))

rownames(Heatmap_Matrix) <- gsub("Unknown Cluster 66","Unknown Cluster 1",rownames(Heatmap_Matrix))

Cluster_Order <- c("GLU Neurons 1", "GLU Neurons 2", "GLU Neurons 3", "GLU Neurons 4", "GLU Neurons 5", "GLU Neurons 6", "GLU Neurons 7", "GLU Neurons 8", "GLU Neurons 9", "GLU Neurons 10", "GLU Neurons 11", "GLU Neurons 12", "GLU Neurons 13", "GLU Neurons 14", "GLU Neurons 15", "GLU Neurons 16", "GLU Neurons 17", "GLU Neurons 18", "GLU Neurons 19", "GLU Neurons 20", "GABA Neurons 1", "GABA Neurons 2", "GABA Neurons 3", "GABA Neurons 4", "GABA Neurons 5", "GABA Neurons 6", "GABA Neurons 7", "GABA Neurons 8", "GABA Neurons 9", "GABA Neurons 10", "GABA Neurons 11", "GABA Neurons 12", "GABA Neurons 13", "GABA Neurons 14", "GABA Neurons 15", "Astrocytes", "Oligodendrocytes", "OPCs", "Microglia", "Endothelial Cells 1", "Endothelial Cells 2", "Unknown Immune Cells", "Unknown Cluster 1")

Heatmap_Matrix <- Heatmap_Matrix[match(Cluster_Order,rownames(Heatmap_Matrix)),]

Heatmap_Matrix <- Heatmap_Matrix[,match(GSEA_Top_Pathways,colnames(Heatmap_Matrix))]

```



```{R}
library(ggplot2)

MYPalette <- colorRampPalette(c("magenta","#C228C8","#813384","#000000","#817E3E","#BEB72F","#FFF300"))(200)

pheatmap(Heatmap_Matrix, border_color = "gray", color = MYPalette, cellwidth = 10, cellheight = 10, breaks = seq(from=-2,to=2, length.out=200), cluster_cols = TRUE, cluster_rows = TRUE)

GSEA_Human_PFC_Heatmap <- pheatmap(Heatmap_Matrix, border_color = "gray", color = MYPalette, cellwidth = 10, cellheight = 10, breaks = seq(from=-2,to=2, length.out=200), cluster_cols = FALSE, cluster_rows = FALSE)

ggsave(GSEA_Human_PFC_Heatmap,filename = "../Figures/GSEA_and_DE_Gene_Heatmaps/ILB_vs_HC/ILB_vs_HC_FullIntegrationOSR_GSEA_C2_TopMostCommon30PathwaysinPDvsHC_Heatmap.pdf", device = "pdf", height = 18, width = 12, units = "in")

```

####################################################################################################

Mitochondrial Gene pathways no pval threshold


```{R}
library(reshape2)
library(dplyr)
library(tidyr)
library(vroom)
library(pheatmap)

#Cell_Type <- gsub("_TREATED_vs_CTRL_GSEA_Sig_Genesets.tsv","",list.files("../Files/Subclusters_GSEA/"))
files <- list.files("../Files/Subclusters_GSEA", full.names = TRUE, pattern = "*_ILB_vs_HC_GSEA_AllGenesets.tsv")
files <- files[grep("PD_and",files,invert = TRUE)]
GSEA_Aggr_Table <- vroom(files, id = "Cell_Type")
GSEA_Aggr_Table$Cell_Type <- gsub("../Files/Subclusters_GSEA/|_ILB_vs_HC_GSEA_AllGenesets.tsv","",GSEA_Aggr_Table$Cell_Type)
#GSEA_Aggr_Table$Cell_Type <- #gsub("GLU_Cajal_Retzius","Cajal-Retzius",GSEA_Aggr_Table$Cell_Type)
```


```{R}

GSEA_Aggr_Table_PvalSorted <- GSEA_Aggr_Table[order(GSEA_Aggr_Table$padj),]

```



```{R}

Pathways <- c("BIOCARTA_PGC1A_PATHWAY","KEGG_OXIDATIVE_PHOSPHORYLATION","WP_ELECTRON_TRANSPORT_CHAIN_OXPHOS_SYSTEM_IN_MITOCHONDRIA","REACTOME_RESPIRATORY_ELECTRON_TRANSPORT_ATP_SYNTHESIS_BY_CHEMIOSMOTIC_COUPLING_AND_HEAT_PRODUCTION_BY_UNCOUPLING_PROTEINS","REACTOME_IRON_UPTAKE_AND_TRANSPORT","KEGG_PARKINSONS_DISEASE","WP_MITOCHONDRIAL_CIV_ASSEMBLY","REACTOME_RESPIRATORY_ELECTRON_TRANSPORT","WP_OXIDATIVE_PHOSPHORYLATION","REACTOME_THE_CITRIC_ACID_TCA_CYCLE_AND_RESPIRATORY_ELECTRON_TRANSPORT","REACTOME_MITOCHONDRIAL_PROTEIN_IMPORT","WP_MITOCHONDRIAL_COMPLEX_I_ASSEMBLY_MODEL_OXPHOS_SYSTEM")

```


Pathways <- c("BIOCARTA_PGC1A_PATHWAY","KEGG_OXIDATIVE_PHOSPHORYLATION","WP_ELECTRON_TRANSPORT_CHAIN_OXPHOS_SYSTEM_IN_MITOCHONDRIA","REACTOME_RESPIRATORY_ELECTRON_TRANSPORT_ATP_SYNTHESIS_BY_CHEMIOSMOTIC_COUPLING_AND_HEAT_PRODUCTION_BY_UNCOUPLING_PROTEINS","REACTOME_IRON_UPTAKE_AND_TRANSPORT")


if (length(index) == 0) {
    NES_subtable <- as.data.frame(rbind(rep(i,length(Pathways),Pathways,rep(0,length(Pathways)))))
    colnames(NES_subtable) <- c("Cell_Type","pathway","NES")
  }
  else {
    NES_subtable <- temp_table[temp_table$pathway %in% Pathways,]
    NES_subtable <- NES_subtable[,c(1,2,7)]
    if (length(NES_subtable$Cell_Type == 8)){
      NES_subtable <- NES_subtable
    }
    else{
      rbind(NES_subtable,as.data.frame(rbind(rep(i,length(Pathways[-index])),Pathways[-index],rep(0,length(Pathways[-index])))))
    }
  }
  Heatmap_Matrix <- cbind(Heatmap_Matrix,NES_subtable)
}

```{R}
library(rlist)
Heatmap_Matrix <- list()
for (i in unique(GSEA_Aggr_Table$Cell_Type)) {
  temp_table <- GSEA_Aggr_Table[GSEA_Aggr_Table$Cell_Type %in% i,]
  index <- which(Pathways %in% temp_table$pathway)
  if (length(index) == 0) {
    NES_subtable <- as.data.frame(cbind(rep(i,length(Pathways)),Pathways,rep(0,length(Pathways))))
    colnames(NES_subtable) <- c("Cell_Type","pathway","NES")
  }
  else {
    NES_subtable <- temp_table[temp_table$pathway %in% Pathways,]
    NES_subtable <- NES_subtable[,c(1,2,7)]
    if (length(NES_subtable$Cell_Type) == 7){
      NES_subtable <- NES_subtable
    }
    else{
      temp_table2 <- as.data.frame(cbind(rep(i,length(Pathways[-index])),Pathways[-index],rep(0,length(Pathways[-index]))))
      colnames(temp_table2) <- c("Cell_Type","pathway","NES")
      NES_subtable <- rbind(NES_subtable,temp_table2)
    }
  }
  Heatmap_Matrix <- list.append(Heatmap_Matrix,NES_subtable)
}

Heatmap_Matrix <- do.call("rbind", Heatmap_Matrix)
```




```{R}
Heatmap_Matrix$NES <- as.numeric(Heatmap_Matrix$NES)
Heatmap_Matrix <- dcast(data = Heatmap_Matrix,formula = Cell_Type~pathway,fun.aggregate = sum,value.var = "NES")
rownames(Heatmap_Matrix) <- Heatmap_Matrix$Cell_Type
Heatmap_Matrix <- Heatmap_Matrix[,-1]


```

doublets: 10,25,28,29

`10` = "GLU_Neurons_6"
`25` = "GABA_Neurons_8"
`28` = "GABA_Neurons_9",
`29` = "GLU_Neurons_12"

```{R}

SubclusterSplitCaseNumbersTable <- read.delim("../Files/Subcluster_SplitCase_NumbersTable.tsv")

Assigned_Clusters <- unique(SubclusterSplitCaseNumbersTable$Var1)

excluded_cells <- Assigned_Clusters[-which(Assigned_Clusters %in% rownames(Heatmap_Matrix))]

#excluded_cells <- gsub("Endothelial_Cells","Endothelial_Cells_and_Microglia",excluded_cells)

#rownames(Heatmap_Matrix) <- gsub("Endothelial_Cells","Endothelial_Cells_and_Microglia",rownames(Heatmap_Matrix))

for (ec in excluded_cells) {
  Heatmap_Matrix <- rbind(Heatmap_Matrix,rep(0,ncol(Heatmap_Matrix)))
  rownames(Heatmap_Matrix)[nrow(Heatmap_Matrix)] <- ec
}

```


```{R}

rownames(Heatmap_Matrix) <- gsub("_"," ",rownames(Heatmap_Matrix))

rownames(Heatmap_Matrix) <- gsub("TEMRA T Cells","Unknown Immune Cells",rownames(Heatmap_Matrix))

rownames(Heatmap_Matrix) <- gsub("Unknown Cluster 66","Unknown Cluster 1",rownames(Heatmap_Matrix))

Cluster_Order <- c("GLU Neurons 1", "GLU Neurons 2", "GLU Neurons 3", "GLU Neurons 4", "GLU Neurons 5", "GLU Neurons 6", "GLU Neurons 7", "GLU Neurons 8", "GLU Neurons 9", "GLU Neurons 10", "GLU Neurons 11", "GLU Neurons 12", "GLU Neurons 13", "GLU Neurons 14", "GLU Neurons 15", "GLU Neurons 16", "GLU Neurons 17", "GLU Neurons 18", "GLU Neurons 19", "GLU Neurons 20", "GABA Neurons 1", "GABA Neurons 2", "GABA Neurons 3", "GABA Neurons 4", "GABA Neurons 5", "GABA Neurons 6", "GABA Neurons 7", "GABA Neurons 8", "GABA Neurons 9", "GABA Neurons 10", "GABA Neurons 11", "GABA Neurons 12", "GABA Neurons 13", "GABA Neurons 14", "GABA Neurons 15", "Astrocytes", "Oligodendrocytes", "OPCs", "Microglia", "Endothelial Cells 1", "Endothelial Cells 2", "Unknown Immune Cells", "Unknown Cluster 1")

Heatmap_Matrix <- Heatmap_Matrix[match(Cluster_Order,rownames(Heatmap_Matrix)),]

```


```{R}
library(ggplot2)

MYPalette <- colorRampPalette(c("magenta","#C228C8","#813384","#000000","#817E3E","#BEB72F","#FFF300"))(200)

pheatmap(Heatmap_Matrix, border_color = "gray", color = MYPalette, cellwidth = 10, cellheight = 10, breaks = seq(from=-2,to=2, length.out=200), cluster_cols = TRUE, cluster_rows = TRUE)

GSEA_Human_PFC_Heatmap <- pheatmap(Heatmap_Matrix, border_color = "gray", color = MYPalette, cellwidth = 10, cellheight = 10, breaks = seq(from=-2,to=2, length.out=200), cluster_cols = FALSE, cluster_rows = FALSE)

ggsave(GSEA_Human_PFC_Heatmap,filename = "../Figures/GSEA_and_DE_Gene_Heatmaps/ILB_vs_HC/ILB_vs_HC_GSEA_C2_Heatmap_NoPvalThreshold_MitochondrialPathways.pdf", device = "pdf", height = 18, width = 12, units = "in")

```


####################################################################################################

Mitochondrial Gene pathways nominal pval 


```{R}
library(reshape2)
library(dplyr)
library(tidyr)
library(vroom)
library(pheatmap)

#Cell_Type <- gsub("_TREATED_vs_CTRL_GSEA_Sig_Genesets.tsv","",list.files("../Files/Subclusters_GSEA/"))
files <- list.files("../Files/Subclusters_GSEA", full.names = TRUE, pattern = "*_ILB_vs_HC_GSEA_AllGenesets.tsv")
files <- files[grep("PD_and",files,invert = TRUE)]
GSEA_Aggr_Table <- vroom(files, id = "Cell_Type")
GSEA_Aggr_Table$Cell_Type <- gsub("../Files/Subclusters_GSEA/|_ILB_vs_HC_GSEA_AllGenesets.tsv","",GSEA_Aggr_Table$Cell_Type)
#GSEA_Aggr_Table$Cell_Type <- #gsub("GLU_Cajal_Retzius","Cajal-Retzius",GSEA_Aggr_Table$Cell_Type)
```


```{R}

#GSEA_Aggr_Table_PvalSorted <- GSEA_Aggr_Table[order(GSEA_Aggr_Table$padj),]

GSEA_Aggr_Table <- GSEA_Aggr_Table[GSEA_Aggr_Table$pval <= 0.05,]

```



```{R}

Pathways <- c("BIOCARTA_PGC1A_PATHWAY","KEGG_OXIDATIVE_PHOSPHORYLATION","WP_ELECTRON_TRANSPORT_CHAIN_OXPHOS_SYSTEM_IN_MITOCHONDRIA","REACTOME_RESPIRATORY_ELECTRON_TRANSPORT_ATP_SYNTHESIS_BY_CHEMIOSMOTIC_COUPLING_AND_HEAT_PRODUCTION_BY_UNCOUPLING_PROTEINS","REACTOME_IRON_UPTAKE_AND_TRANSPORT","KEGG_PARKINSONS_DISEASE","WP_MITOCHONDRIAL_CIV_ASSEMBLY","REACTOME_RESPIRATORY_ELECTRON_TRANSPORT","WP_OXIDATIVE_PHOSPHORYLATION","REACTOME_THE_CITRIC_ACID_TCA_CYCLE_AND_RESPIRATORY_ELECTRON_TRANSPORT","REACTOME_MITOCHONDRIAL_PROTEIN_IMPORT","WP_MITOCHONDRIAL_COMPLEX_I_ASSEMBLY_MODEL_OXPHOS_SYSTEM")

```


Pathways <- c("BIOCARTA_PGC1A_PATHWAY","KEGG_OXIDATIVE_PHOSPHORYLATION","WP_ELECTRON_TRANSPORT_CHAIN_OXPHOS_SYSTEM_IN_MITOCHONDRIA","REACTOME_RESPIRATORY_ELECTRON_TRANSPORT_ATP_SYNTHESIS_BY_CHEMIOSMOTIC_COUPLING_AND_HEAT_PRODUCTION_BY_UNCOUPLING_PROTEINS","REACTOME_IRON_UPTAKE_AND_TRANSPORT")


if (length(index) == 0) {
    NES_subtable <- as.data.frame(rbind(rep(i,length(Pathways),Pathways,rep(0,length(Pathways)))))
    colnames(NES_subtable) <- c("Cell_Type","pathway","NES")
  }
  else {
    NES_subtable <- temp_table[temp_table$pathway %in% Pathways,]
    NES_subtable <- NES_subtable[,c(1,2,7)]
    if (length(NES_subtable$Cell_Type == 8)){
      NES_subtable <- NES_subtable
    }
    else{
      rbind(NES_subtable,as.data.frame(rbind(rep(i,length(Pathways[-index])),Pathways[-index],rep(0,length(Pathways[-index])))))
    }
  }
  Heatmap_Matrix <- cbind(Heatmap_Matrix,NES_subtable)
}

```{R}
library(rlist)
Heatmap_Matrix <- list()
for (i in unique(GSEA_Aggr_Table$Cell_Type)) {
  temp_table <- GSEA_Aggr_Table[GSEA_Aggr_Table$Cell_Type %in% i,]
  index <- which(Pathways %in% temp_table$pathway)
  if (length(index) == 0) {
    NES_subtable <- as.data.frame(cbind(rep(i,length(Pathways)),Pathways,rep(0,length(Pathways))))
    colnames(NES_subtable) <- c("Cell_Type","pathway","NES")
  }
  else {
    NES_subtable <- temp_table[temp_table$pathway %in% Pathways,]
    NES_subtable <- NES_subtable[,c(1,2,7)]
    if (length(NES_subtable$Cell_Type) == 7){
      NES_subtable <- NES_subtable
    }
    else{
      temp_table2 <- as.data.frame(cbind(rep(i,length(Pathways[-index])),Pathways[-index],rep(0,length(Pathways[-index]))))
      colnames(temp_table2) <- c("Cell_Type","pathway","NES")
      NES_subtable <- rbind(NES_subtable,temp_table2)
    }
  }
  Heatmap_Matrix <- list.append(Heatmap_Matrix,NES_subtable)
}

Heatmap_Matrix <- do.call("rbind", Heatmap_Matrix)
```




```{R}
Heatmap_Matrix$NES <- as.numeric(Heatmap_Matrix$NES)
Heatmap_Matrix <- dcast(data = Heatmap_Matrix,formula = Cell_Type~pathway,fun.aggregate = sum,value.var = "NES")
rownames(Heatmap_Matrix) <- Heatmap_Matrix$Cell_Type
Heatmap_Matrix <- Heatmap_Matrix[,-1]


```

doublets: 10,25,28,29

`10` = "GLU_Neurons_6"
`25` = "GABA_Neurons_8"
`28` = "GABA_Neurons_9",
`29` = "GLU_Neurons_12"

```{R}

SubclusterSplitCaseNumbersTable <- read.delim("../Files/Subcluster_SplitCase_NumbersTable.tsv")

Assigned_Clusters <- unique(SubclusterSplitCaseNumbersTable$Var1)

excluded_cells <- Assigned_Clusters[-which(Assigned_Clusters %in% rownames(Heatmap_Matrix))]

#excluded_cells <- gsub("Endothelial_Cells","Endothelial_Cells_and_Microglia",excluded_cells)

#rownames(Heatmap_Matrix) <- gsub("Endothelial_Cells","Endothelial_Cells_and_Microglia",rownames(Heatmap_Matrix))

for (ec in excluded_cells) {
  Heatmap_Matrix <- rbind(Heatmap_Matrix,rep(0,ncol(Heatmap_Matrix)))
  rownames(Heatmap_Matrix)[nrow(Heatmap_Matrix)] <- ec
}

```


```{R}

rownames(Heatmap_Matrix) <- gsub("_"," ",rownames(Heatmap_Matrix))

rownames(Heatmap_Matrix) <- gsub("TEMRA T Cells","Unknown Immune Cells",rownames(Heatmap_Matrix))

rownames(Heatmap_Matrix) <- gsub("Unknown Cluster 66","Unknown Cluster 1",rownames(Heatmap_Matrix))

Cluster_Order <- c("GLU Neurons 1", "GLU Neurons 2", "GLU Neurons 3", "GLU Neurons 4", "GLU Neurons 5", "GLU Neurons 6", "GLU Neurons 7", "GLU Neurons 8", "GLU Neurons 9", "GLU Neurons 10", "GLU Neurons 11", "GLU Neurons 12", "GLU Neurons 13", "GLU Neurons 14", "GLU Neurons 15", "GLU Neurons 16", "GLU Neurons 17", "GLU Neurons 18", "GLU Neurons 19", "GLU Neurons 20", "GABA Neurons 1", "GABA Neurons 2", "GABA Neurons 3", "GABA Neurons 4", "GABA Neurons 5", "GABA Neurons 6", "GABA Neurons 7", "GABA Neurons 8", "GABA Neurons 9", "GABA Neurons 10", "GABA Neurons 11", "GABA Neurons 12", "GABA Neurons 13", "GABA Neurons 14", "GABA Neurons 15", "Astrocytes", "Oligodendrocytes", "OPCs", "Microglia", "Endothelial Cells 1", "Endothelial Cells 2", "Unknown Immune Cells", "Unknown Cluster 1")

Heatmap_Matrix <- Heatmap_Matrix[match(Cluster_Order,rownames(Heatmap_Matrix)),]

```


```{R}
library(ggplot2)

MYPalette <- colorRampPalette(c("magenta","#C228C8","#813384","#000000","#817E3E","#BEB72F","#FFF300"))(200)

pheatmap(Heatmap_Matrix, border_color = "gray", color = MYPalette, cellwidth = 10, cellheight = 10, breaks = seq(from=-2,to=2, length.out=200), cluster_cols = TRUE, cluster_rows = TRUE)

GSEA_Human_PFC_Heatmap <- pheatmap(Heatmap_Matrix, border_color = "gray", color = MYPalette, cellwidth = 10, cellheight = 10, breaks = seq(from=-2,to=2, length.out=200), cluster_cols = FALSE, cluster_rows = FALSE)

ggsave(GSEA_Human_PFC_Heatmap,filename = "../Figures/GSEA_and_DE_Gene_Heatmaps/ILB_vs_HC/ILB_vs_HC_GSEA_C2_Heatmap_NominalPvalue_MitochondrialPathways.pdf", device = "pdf", height = 18, width = 12, units = "in")

```












