---
title: "Seurat Workflow for Microglia Subclustering"
output: html_document
---


```{R}

library(Seurat)
library(cowplot)
library(ggplot2)
library(ggsci)
library(dplyr)
library(psych)
library(pheatmap)
library(harmony)
#library(clusterProfiler)
#library(org.Hs.eg.db)
library(DOSE)
library(GOSemSim)
library(enrichplot)
library(glmpca)
library(SeuratWrappers)
library(stringr)
library(MAST)
library(reshape2)

SeuratObjectMicroglia <- readRDS("../Files/FullIntegrationOSR_MTG_SeuratFinal_MicrogliaSubset.rds")

```

TAKEN OUT SAMPLE ID, MAYBE ADD BACK IN LATER DEPENDING?
```{R}

SeuratObjectMicroglia <- FindVariableFeatures(SeuratObjectMicroglia, selection.method = "vst", nfeatures = 2000)

all.genes <- rownames(SeuratObjectMicroglia)

SeuratObjectMicroglia <- ScaleData(SeuratObjectMicroglia, features = all.genes, verbose = FALSE)

SeuratObjectMicroglia <- RunGLMPCA(SeuratObjectMicroglia, features=SeuratObjectMicroglia@assays$RNA@var.features, L = 40)

SeuratObjectMicroglia <- RunHarmony(SeuratObjectMicroglia, group.by.vars = c("batch","age_bracket","sex"), plot_convergence = TRUE, reduction = "glmpca", theta = c(0.5,0.5,0.5,0.5))

#SeuratObjectMicroglia <- RunHarmony(SeuratObjectMicroglia, group.by.vars = c("batch","age_bracket","sex"), plot_convergence = TRUE, reduction = "glmpca", theta = c(0.66,0.66,0.66))

```

```{R}

ElbowPlot(SeuratObjectMicroglia, reduction = "harmony",ndims = 40)

```



```{R}
SeuratObjectMicroglia <- FindNeighbors(SeuratObjectMicroglia, reduction = "harmony", dims = 1:21)
SeuratObjectMicroglia <- FindClusters(SeuratObjectMicroglia, algorithm = 4, method = "igraph", resolution = 0.6)
```


```{r}
SeuratObjectMicroglia <- RunUMAP(SeuratObjectMicroglia, reduction = "harmony", dims = 1:21)
```



```{R}

DimPlot(SeuratObjectMicroglia, reduction = "umap", label = TRUE, pt.size = 0.01, label.size=2.5, repel = TRUE) + 
  theme(axis.text = element_text(size=8),
        axis.title = element_text(size = 12),
        legend.text = element_text(size = 8),
        title = element_text(size = 12),
        legend.key.size = unit(0.4,"cm"))




```


```{R}

VlnPlot(SeuratObjectMicroglia, "P2RY12")

ClusterFrame <- as.data.frame(table(Idents(SeuratObjectMicroglia), SeuratObjectMicroglia$case))

test <- group_by(ClusterFrame,Var2) %>% mutate(percentcluster=(Freq/sum(Freq))*100)

test2 <- dcast(test, Var1~Var2)

```

#########################################################################################################################


Alternative


```{R}

library(Seurat)
library(cowplot)
library(ggplot2)
library(ggsci)
library(dplyr)
library(psych)
library(pheatmap)
library(harmony)
#library(clusterProfiler)
#library(org.Hs.eg.db)
library(DOSE)
library(GOSemSim)
library(enrichplot)
library(glmpca)
library(SeuratWrappers)
library(stringr)
library(MAST)
library(reshape2)

TempObject <- readRDS("../Files/FullIntegrationOSR_MTG_SeuratFinal_MicrogliaSubset.rds")

```

```{R}

MicrogliaCounts <- TempObject@assays$RNA@counts

MicrogliaMetadata <- TempObject@meta.data

SeuratObjectMicroglia <- CreateSeuratObject(counts = MicrogliaCounts,
                            project = "FIOR_Microglia")


SeuratObjectMicroglia@meta.data <- MicrogliaMetadata


```



```{R}

SeuratObjectMicroglia <- NormalizeData(SeuratObjectMicroglia, normalization.method = "LogNormalize", scale.factor = 10000)

SeuratObjectMicroglia <- FindVariableFeatures(SeuratObjectMicroglia, selection.method = "vst", nfeatures = 2000)

all.genes <- rownames(SeuratObjectMicroglia)

SeuratObjectMicroglia <- ScaleData(SeuratObjectMicroglia, features = all.genes, verbose = FALSE)

SeuratObjectMicroglia <- RunGLMPCA(SeuratObjectMicroglia, features=SeuratObjectMicroglia@assays$RNA@var.features, L = 50)


```


```{R}
SeuratObjectMicroglia <- RunHarmony(SeuratObjectMicroglia, group.by.vars = c("sample_id","batch","age_bracket","sex"), plot_convergence = TRUE, reduction = "glmpca", theta = c(0.5,0.5,0.5,0.5))



```


```{R}

ElbowPlot(SeuratObjectMicroglia, reduction = "harmony",ndims = 50)

```

```{R}
SeuratObjectMicroglia <- FindNeighbors(SeuratObjectMicroglia, reduction = "harmony", dims = 1:30)
SeuratObjectMicroglia <- FindClusters(SeuratObjectMicroglia, algorithm = 4, method = "igraph")
```

```{r}
SeuratObjectMicroglia <- RunUMAP(SeuratObjectMicroglia, reduction = "harmony", dims = 1:30)
```



```{R}

DimPlot(SeuratObjectMicroglia, reduction = "umap", label = TRUE, pt.size = 0.01, label.size=2.5, repel = TRUE) + 
  theme(axis.text = element_text(size=8),
        axis.title = element_text(size = 12),
        legend.text = element_text(size = 8),
        title = element_text(size = 12),
        legend.key.size = unit(0.4,"cm"))

```


```{R}

VlnPlot(SeuratObjectMicroglia, "P2RY12")

```


```{R}

VlnPlot(SeuratObjectMicroglia, "AIF1")

```

CD16 profinflammatory 

```{R}

VlnPlot(SeuratObjectMicroglia, "FCGR3A")

```
```{R}

VlnPlot(SeuratObjectMicroglia, "CD163")

```
```{R}

VlnPlot(SeuratObjectMicroglia, "MRC1")

```



```{R}

ClusterFrame <- as.data.frame(table(Idents(SeuratObjectMicroglia), SeuratObjectMicroglia$case))

test <- group_by(ClusterFrame,Var2) %>% mutate(percentcluster=(Freq/sum(Freq))*100)

test2 <- dcast(test, Var1~Var2)

```



########################################################################################################################



Alternative 2



```{R}

library(Seurat)
library(cowplot)
library(ggplot2)
library(ggsci)
library(dplyr)
library(psych)
library(pheatmap)
library(harmony)
#library(clusterProfiler)
#library(org.Hs.eg.db)
library(DOSE)
library(GOSemSim)
library(enrichplot)
library(glmpca)
library(SeuratWrappers)
library(stringr)
library(MAST)
library(reshape2)

TempObject <- readRDS("../Files/FullIntegrationOSR_MTG_SeuratFinal_MicrogliaSubset.rds")

```

```{R}

MicrogliaCounts <- TempObject@assays$RNA@counts

MicrogliaMetadata <- TempObject@meta.data

SeuratObjectMicroglia <- CreateSeuratObject(counts = MicrogliaCounts,
                            project = "FIOR_Microglia")


SeuratObjectMicroglia@meta.data <- MicrogliaMetadata


```



```{R}

SeuratObjectMicroglia <- NormalizeData(SeuratObjectMicroglia, normalization.method = "LogNormalize", scale.factor = 10000)

SeuratObjectMicroglia <- FindVariableFeatures(SeuratObjectMicroglia, selection.method = "vst", nfeatures = 2000)

all.genes <- rownames(SeuratObjectMicroglia)

SeuratObjectMicroglia <- ScaleData(SeuratObjectMicroglia, features = all.genes, verbose = FALSE)

SeuratObjectMicroglia <- RunGLMPCA(SeuratObjectMicroglia, features=SeuratObjectMicroglia@assays$RNA@var.features, L = 40)


```


```{R}

#SeuratObjectMicroglia <- RunHarmony(SeuratObjectMicroglia, group.by.vars = c("sample_id","batch","age_bracket","sex"), plot_convergence = TRUE, reduction = "glmpca", theta = c(0.5,0.5,0.5,0.5))

SeuratObjectMicroglia <- RunHarmony(SeuratObjectMicroglia, group.by.vars = c("batch","age_bracket","sex"), plot_convergence = TRUE, reduction = "glmpca", theta = c(0.66,0.66,0.66))

```


```{R}

ElbowPlot(SeuratObjectMicroglia, reduction = "harmony",ndims = 40)

```

```{R}
SeuratObjectMicroglia <- FindNeighbors(SeuratObjectMicroglia, reduction = "harmony", dims = 1:30)
SeuratObjectMicroglia <- FindClusters(SeuratObjectMicroglia, algorithm = 4, method = "igraph", resolution = 0.6)
```

```{r}
SeuratObjectMicroglia <- RunUMAP(SeuratObjectMicroglia, reduction = "harmony", dims = 1:30)
```


```{R}

DimPlot(SeuratObjectMicroglia, reduction = "umap", label = TRUE, pt.size = 0.01, label.size=2.5, repel = TRUE) + 
  theme(axis.text = element_text(size=8),
        axis.title = element_text(size = 12),
        legend.text = element_text(size = 8),
        title = element_text(size = 12),
        legend.key.size = unit(0.4,"cm"))

```

#############################################################################################################



Alternative 3



```{R}

library(Seurat)
library(cowplot)
library(ggplot2)
library(ggsci)
library(dplyr)
library(psych)
library(pheatmap)
library(harmony)
#library(clusterProfiler)
#library(org.Hs.eg.db)
library(DOSE)
library(GOSemSim)
library(enrichplot)
library(glmpca)
library(SeuratWrappers)
library(stringr)
library(MAST)
library(reshape2)

TempObject <- readRDS("../Files/FullIntegrationOSR_MTG_SeuratFinal_MicrogliaSubset.rds")

```

```{R}

MicrogliaCounts <- TempObject@assays$RNA@counts

MicrogliaMetadata <- TempObject@meta.data

SeuratObjectMicroglia <- CreateSeuratObject(counts = MicrogliaCounts,
                            project = "FIOR_Microglia")


SeuratObjectMicroglia@meta.data <- MicrogliaMetadata


```



```{R}

SeuratObjectMicroglia <- NormalizeData(SeuratObjectMicroglia, normalization.method = "LogNormalize", scale.factor = 10000)

SeuratObjectMicroglia <- FindVariableFeatures(SeuratObjectMicroglia, selection.method = "vst", nfeatures = 2000)

all.genes <- rownames(SeuratObjectMicroglia)

SeuratObjectMicroglia <- ScaleData(SeuratObjectMicroglia, features = all.genes, verbose = FALSE)

SeuratObjectMicroglia <- RunGLMPCA(SeuratObjectMicroglia, features=SeuratObjectMicroglia@assays$RNA@var.features, L = 40)


```


```{R}

SeuratObjectMicroglia <- RunHarmony(SeuratObjectMicroglia, group.by.vars = c("sample_id","batch","age_bracket","sex"), plot_convergence = TRUE, reduction = "glmpca", theta = c(0.5,0.5,0.5,0.5))


```


```{R}

ElbowPlot(SeuratObjectMicroglia, reduction = "harmony",ndims = 40)

```

```{R}
SeuratObjectMicroglia <- FindNeighbors(SeuratObjectMicroglia, reduction = "harmony", dims = 1:30)
SeuratObjectMicroglia <- FindClusters(SeuratObjectMicroglia, algorithm = 4, method = "igraph", resolution = 0.6)
```

```{r}
SeuratObjectMicroglia <- RunUMAP(SeuratObjectMicroglia, reduction = "harmony", dims = 1:30)
```


```{R}

DimPlot(SeuratObjectMicroglia, reduction = "umap", label = TRUE, pt.size = 0.01, label.size=2.5, repel = TRUE) + 
  theme(axis.text = element_text(size=8),
        axis.title = element_text(size = 12),
        legend.text = element_text(size = 8),
        title = element_text(size = 12),
        legend.key.size = unit(0.4,"cm"))

```







