---
title: "Performing DESeq2 DE Analysis and making tables for GSE"
output: html_document
---

```{R, message=FALSE}
library(Seurat)
library(cowplot)
library(ggplot2)
library(ggsci)
library(dplyr)
library(psych)
library(pheatmap)
library(harmony)
#library(clusterProfiler)
#library(org.Hs.eg.db)
library(DOSE)
library(GOSemSim)
library(enrichplot)
library(sciplot)
library(reshape2)
library(MAST)
library(DESeq2)
library(Matrix.utils)
library(stringr)
```



```{R}
Batch567_MTG=readRDS("Files/Batch567_Unassigned.rds")
Batch567_MTG@meta.data$batch <- gsub("Batch56767","Batch5",Batch567_MTG@meta.data$batch)
```


```{R}
Batch567_MTG$case <- gsub("ILB","PD",Batch567_MTG$case)
case_clusters <- paste(Batch567_MTG$case,Batch567_MTG$seurat_clusters,sep = "_")
```


```{R}
Batch567_MTG <- RenameIdents(Batch567_MTG, `0` = "Oligodendrocytes", `1` = "GLU Neurons", `2` = "GLU Neurons",
                      `3` = "GLU Neurons", `4` = "GABA Neurons", `5` = "GABA Neurons",
                      `6` = "GLU Neurons", `7` = "Astrocytes", `8` = "GLU Neurons",`9` = "GABA Neurons",
                      `10` = "GLU Neurons", `11` = "GLU Neurons",`12` = "GLU Neurons",
                      `13` = "Microglia",`14` = "Astrocytes",
                      `15` = "Oligodendrocytes", `16`="GABA Neurons", `17`="GLU Neurons", `18`="Endothelial",`19`="Endothelial",`20`="Oligodendrocytes",`21`="GABA Neurons",`22`="GABA Neurons")
```


```{R}
Astrocytes <- subset(Batch567_MTG, idents = "Astrocytes")

Idents(Astrocytes) <- "case"

#Performing DESeq differential expression analysis

#remove lowly expressed genes

Astrocytes_Filter <- Astrocytes[rowSums(Astrocytes@assays$RNA@counts) >= 10, ]

#grab counts, create aggrtable and aggregate based on sample and condition

Astrocyte_Counts <- Astrocytes_Filter@assays$RNA@counts

coldata <- data.frame(as.vector(Astrocytes_Filter$case),as.vector(Astrocytes_Filter$sample_ID))

row.names(coldata) <- colnames(Astrocyte_Counts)

colnames(coldata) <- c("Case","Sample")

Astrocyte_Counts_Aggr <- t(aggregate.Matrix(t(Astrocyte_Counts), 
                       groupings = coldata, fun = "sum"))

#check colnames to see if aggregation has worked and create a coldata table for DESeq2

colnames(Astrocyte_Counts_Aggr)

coldata_aggr <- data.frame(factor(str_extract(colnames(Astrocyte_Counts_Aggr),"PD|HC")),factor(gsub("HC_|PD_","",colnames(Astrocyte_Counts_Aggr))))

colnames(coldata_aggr) <- c("Case","Sample")

Astrocytedds <- DESeqDataSetFromMatrix(countData = Astrocyte_Counts_Aggr,
                       colData = coldata_aggr,
                       design = ~ Case)

AstrocyteddsDESeq <- DESeq(Astrocytedds)

resultsNames(AstrocyteddsDESeq)

AstrocytesRes <- results(AstrocyteddsDESeq,name="Case_PD_vs_HC")

AstrocytesRes_filter <- AstrocytesRes[!is.na(AstrocytesRes$padj),]

AstrocytesRes_pvalfilter <- AstrocytesRes_filter[AstrocytesRes_filter$padj <= 0.05,]

AstrocytesRes_pvalfilter
```

```{R}

AstrocyteNormalisedCounts <- data.frame(counts(AstrocyteddsDESeq, normalized = TRUE))

AstrocyteNormalisedCounts <- cbind(rep(NA,length(AstrocyteNormalisedCounts[,1])),AstrocyteNormalisedCounts)

AstrocyteNormalisedCounts <- cbind(rownames(AstrocyteNormalisedCounts),AstrocyteNormalisedCounts)

colnames(AstrocyteNormalisedCounts)[c(1,2)] <- c("NAME","description")

test <- rbind(colnames(AstrocyteNormalisedCounts), AstrocyteNormalisedCounts)

test <- rbind(c(nrow(AstrocyteNormalisedCounts),ncol(AstrocyteNormalisedCounts) -2,rep("",ncol(AstrocyteNormalisedCounts)-2)),test)

test <- rbind(c("#1.2",rep("",ncol(AstrocyteNormalisedCounts))),test)

#write.table(AstrocyteNormalisedCounts, "Files/AstrocyteNormalisedCounts.txt",sep = "\t", row.names = FALSE,quote = FALSE)
```


```{R}
TestAstrocyteNormalisedCounts <- AstrocyteNormalisedCounts

header1 <- c("#")

write.table(TestAstrocyteNormalisedCounts, "Files/Test_AstrocyteNormalisedCounts.txt",sep = "\t", row.names = FALSE,quote = FALSE)
```


```{R}

PhenotypeFile <- data.frame(rbind(as.vector(str_extract(colnames(Astrocyte_Counts_Aggr),"PD|HC"))))

write.table(PhenotypeFile, "Files/PhenotypeFile.txt",sep = "\t", row.names = FALSE, col.names = FALSE, quote = FALSE)
```

```{R}
Microglia <- subset(Batch567_MTG, idents = "Microglia")

Idents(Microglia) <- "case"

```


```{R}

#remove lowly expressed genes

Microglia_Filter <- Microglia[rowSums(Microglia@assays$RNA@counts) >= 10, ]

#grab counts, create aggrtable and aggregate based on sample and condition

Microglia_Counts <- Microglia_Filter@assays$RNA@counts

coldata <- data.frame(as.vector(Microglia_Filter$case),as.vector(Microglia_Filter$sample_ID))

row.names(coldata) <- colnames(Microglia_Counts)

colnames(coldata) <- c("Case","Sample")

Microglia_Counts_Aggr <- t(aggregate.Matrix(t(Microglia_Counts), 
                       groupings = coldata, fun = "sum"))

#check colnames to see if aggregation has worked and create a coldata table for DESeq2

colnames(Microglia_Counts_Aggr)

coldata_aggr <- data.frame(factor(str_extract(colnames(Microglia_Counts_Aggr),"PD|HC")),factor(gsub("HC_|PD_","",colnames(Microglia_Counts_Aggr))))

colnames(coldata_aggr) <- c("Case","Sample")

Microgliadds <- DESeqDataSetFromMatrix(countData = Microglia_Counts_Aggr,
                       colData = coldata_aggr,
                       design = ~ Case)

MicrogliaddsDESeq <- DESeq(Microgliadds)

resultsNames(MicrogliaddsDESeq)

MicrogliaRes <- results(MicrogliaddsDESeq,name="Case_PD_vs_HC")

MicrogliaRes_filter <- MicrogliaRes[!is.na(MicrogliaRes$padj),]

MicrogliaRes_pvalfilter <- MicrogliaRes_filter[MicrogliaRes_filter$padj <= 0.05,]

MicrogliaRes_pvalfilter

```

```{R}

MicrogliaNormalisedCounts <- data.frame(counts(MicrogliaddsDESeq, normalized = TRUE))

MicrogliaNormalisedCounts <- cbind(rep(NA,length(MicrogliaNormalisedCounts[,1])),MicrogliaNormalisedCounts)

MicrogliaNormalisedCounts <- cbind(rownames(MicrogliaNormalisedCounts),MicrogliaNormalisedCounts)

colnames(MicrogliaNormalisedCounts)[c(1,2)] <- c("NAME","description")

write.table(MicrogliaNormalisedCounts, "Files/MicrogliaNormalisedCounts.txt",sep = "\t", row.names = FALSE,quote = FALSE)

```

```{R}
Oligodendrocytes <- subset(Batch567_MTG, idents = "Oligodendrocytes")

Idents(Oligodendrocytes) <- "case"

```


```{R}

#remove lowly expressed genes

Oligodendrocytes_Filter <- Oligodendrocytes[rowSums(Oligodendrocytes@assays$RNA@counts) >= 10, ]

#grab counts, create aggrtable and aggregate based on sample and condition

Oligodendrocytes_Counts <- Oligodendrocytes_Filter@assays$RNA@counts

coldata <- data.frame(as.vector(Oligodendrocytes_Filter$case),as.vector(Oligodendrocytes_Filter$sample_ID))

row.names(coldata) <- colnames(Oligodendrocytes_Counts)

colnames(coldata) <- c("Case","Sample")

Oligodendrocytes_Counts_Aggr <- t(aggregate.Matrix(t(Oligodendrocytes_Counts), 
                       groupings = coldata, fun = "sum"))

#check colnames to see if aggregation has worked and create a coldata table for DESeq2

colnames(Oligodendrocytes_Counts_Aggr)

coldata_aggr <- data.frame(factor(str_extract(colnames(Oligodendrocytes_Counts_Aggr),"PD|HC")),factor(gsub("HC_|PD_","",colnames(Oligodendrocytes_Counts_Aggr))))

colnames(coldata_aggr) <- c("Case","Sample")

Oligodendrocytesdds <- DESeqDataSetFromMatrix(countData = Oligodendrocytes_Counts_Aggr,
                       colData = coldata_aggr,
                       design = ~ Case)

OligodendrocytesddsDESeq <- DESeq(Oligodendrocytesdds)

resultsNames(OligodendrocytesddsDESeq)

OligodendrocytesRes <- results(OligodendrocytesddsDESeq,name="Case_PD_vs_HC")

OligodendrocytesRes_filter <- OligodendrocytesRes[!is.na(OligodendrocytesRes$padj),]

OligodendrocytesRes_pvalfilter <- OligodendrocytesRes_filter[OligodendrocytesRes_filter$padj <= 0.05,]

OligodendrocytesRes_pvalfilter

```


```{R}

OligodendrocytesNormalisedCounts <- data.frame(counts(OligodendrocytesddsDESeq, normalized = TRUE))

OligodendrocytesNormalisedCounts <- cbind(rep(NA,length(OligodendrocytesNormalisedCounts[,1])),OligodendrocytesNormalisedCounts)

OligodendrocytesNormalisedCounts <- cbind(rownames(OligodendrocytesNormalisedCounts),OligodendrocytesNormalisedCounts)

colnames(OligodendrocytesNormalisedCounts)[c(1,2)] <- c("NAME","description")

write.table(OligodendrocytesNormalisedCounts, "Files/OligodendrocytesNormalisedCounts.txt",sep = "\t", row.names = FALSE,quote = FALSE)

```


```{R}
GLU_Neurons <- subset(Batch567_MTG, idents = "GLU Neurons")

Idents(GLU_Neurons) <- "case"

```


```{R}

#remove lowly expressed genes

GLU_Neurons_Filter <- GLU_Neurons[rowSums(GLU_Neurons@assays$RNA@counts) >= 10, ]

#grab counts, create aggrtable and aggregate based on sample and condition

GLU_Neurons_Counts <- GLU_Neurons_Filter@assays$RNA@counts

coldata <- data.frame(as.vector(GLU_Neurons_Filter$case),as.vector(GLU_Neurons_Filter$sample_ID))

row.names(coldata) <- colnames(GLU_Neurons_Counts)

colnames(coldata) <- c("Case","Sample")

GLU_Neurons_Counts_Aggr <- t(aggregate.Matrix(t(GLU_Neurons_Counts), 
                       groupings = coldata, fun = "sum"))

#check colnames to see if aggregation has worked and create a coldata table for DESeq2

colnames(GLU_Neurons_Counts_Aggr)

coldata_aggr <- data.frame(factor(str_extract(colnames(GLU_Neurons_Counts_Aggr),"PD|HC")),factor(gsub("HC_|PD_","",colnames(GLU_Neurons_Counts_Aggr))))

colnames(coldata_aggr) <- c("Case","Sample")

GLU_Neuronsdds <- DESeqDataSetFromMatrix(countData = GLU_Neurons_Counts_Aggr,
                       colData = coldata_aggr,
                       design = ~ Case)

GLU_NeuronsddsDESeq <- DESeq(GLU_Neuronsdds)

resultsNames(GLU_NeuronsddsDESeq)

GLU_NeuronsRes <- results(GLU_NeuronsddsDESeq,name="Case_PD_vs_HC")

GLU_NeuronsRes_filter <- GLU_NeuronsRes[!is.na(GLU_NeuronsRes$padj),]

GLU_NeuronsRes_pvalfilter <- GLU_NeuronsRes_filter[GLU_NeuronsRes_filter$padj <= 0.05,]

GLU_NeuronsRes_pvalfilter

```

Looking at some choice genes

```{R}
GLU_Neurons_Counts_Aggr[rownames(GLU_Neurons_Counts_Aggr) %in% "LEPR",]

GLU_Neurons_Counts_Aggr[rownames(GLU_Neurons_Counts_Aggr) %in% "WDR64",]

```

```{R}

GLU_NeuronsNormalisedCounts <- data.frame(counts(GLU_NeuronsddsDESeq, normalized = TRUE))

GLU_NeuronsNormalisedCounts <- cbind(rep(NA,length(GLU_NeuronsNormalisedCounts[,1])),GLU_NeuronsNormalisedCounts)

GLU_NeuronsNormalisedCounts <- cbind(rownames(GLU_NeuronsNormalisedCounts),GLU_NeuronsNormalisedCounts)

colnames(GLU_NeuronsNormalisedCounts)[c(1,2)] <- c("NAME","description")

write.table(GLU_NeuronsNormalisedCounts, "Files/GLU_NeuronsNormalisedCounts.txt",sep = "\t", row.names = FALSE,quote = FALSE)
```


```{R}
GABA_Neurons <- subset(Batch567_MTG, idents = "GABA Neurons")

Idents(GABA_Neurons) <- "case"

```


```{R}

#remove lowly expressed genes

GABA_Neurons_Filter <- GABA_Neurons[rowSums(GABA_Neurons@assays$RNA@counts) >= 10, ]

#grab counts, create aggrtable and aggregate based on sample and condition

GABA_Neurons_Counts <- GABA_Neurons_Filter@assays$RNA@counts

coldata <- data.frame(as.vector(GABA_Neurons_Filter$case),as.vector(GABA_Neurons_Filter$sample_ID))

row.names(coldata) <- colnames(GABA_Neurons_Counts)

colnames(coldata) <- c("Case","Sample")

GABA_Neurons_Counts_Aggr <- t(aggregate.Matrix(t(GABA_Neurons_Counts), 
                       groupings = coldata, fun = "sum"))

#check colnames to see if aggregation has worked and create a coldata table for DESeq2

colnames(GABA_Neurons_Counts_Aggr)

coldata_aggr <- data.frame(factor(str_extract(colnames(GABA_Neurons_Counts_Aggr),"PD|HC")),factor(gsub("HC_|PD_","",colnames(GABA_Neurons_Counts_Aggr))))

colnames(coldata_aggr) <- c("Case","Sample")

GABA_Neuronsdds <- DESeqDataSetFromMatrix(countData = GABA_Neurons_Counts_Aggr,
                       colData = coldata_aggr,
                       design = ~ Case)

GABA_NeuronsddsDESeq <- DESeq(GABA_Neuronsdds)

resultsNames(GABA_NeuronsddsDESeq)

GABA_NeuronsRes <- results(GABA_NeuronsddsDESeq,name="Case_PD_vs_HC")

GABA_NeuronsRes_filter <- GABA_NeuronsRes[!is.na(GABA_NeuronsRes$padj),]

GABA_NeuronsRes_pvalfilter <- GABA_NeuronsRes_filter[GABA_NeuronsRes_filter$padj <= 0.05,]

GABA_NeuronsRes_pvalfilter

```

```{R}

GABA_NeuronsNormalisedCounts <- data.frame(counts(GABA_NeuronsddsDESeq, normalized = TRUE))

GABA_NeuronsNormalisedCounts <- cbind(rep(NA,length(GABA_NeuronsNormalisedCounts[,1])),GABA_NeuronsNormalisedCounts)

GABA_NeuronsNormalisedCounts <- cbind(rownames(GABA_NeuronsNormalisedCounts),GABA_NeuronsNormalisedCounts)

colnames(GABA_NeuronsNormalisedCounts)[c(1,2)] <- c("NAME","description")

write.table(GABA_NeuronsNormalisedCounts, "Files/GABA_NeuronsNormalisedCounts.txt",sep = "\t", row.names = FALSE,quote = FALSE)

```


```{R}
Endothelial <- subset(Batch567_MTG, idents = "Endothelial")

Idents(Endothelial) <- "case"

```


```{R}

#remove lowly expressed genes

Endothelial_Filter <- Endothelial[rowSums(Endothelial@assays$RNA@counts) >= 10, ]

#grab counts, create aggrtable and aggregate based on sample and condition

Endothelial_Counts <- Endothelial_Filter@assays$RNA@counts

coldata <- data.frame(as.vector(Endothelial_Filter$case),as.vector(Endothelial_Filter$sample_ID))

row.names(coldata) <- colnames(Endothelial_Counts)

colnames(coldata) <- c("Case","Sample")

Endothelial_Counts_Aggr <- t(aggregate.Matrix(t(Endothelial_Counts), 
                       groupings = coldata, fun = "sum"))

#check colnames to see if aggregation has worked and create a coldata table for DESeq2

colnames(Endothelial_Counts_Aggr)

coldata_aggr <- data.frame(factor(str_extract(colnames(Endothelial_Counts_Aggr),"PD|HC")),factor(gsub("HC_|PD_","",colnames(Endothelial_Counts_Aggr))))

colnames(coldata_aggr) <- c("Case","Sample")

Endothelialdds <- DESeqDataSetFromMatrix(countData = Endothelial_Counts_Aggr,
                       colData = coldata_aggr,
                       design = ~ Case)

EndothelialddsDESeq <- DESeq(Endothelialdds)

resultsNames(EndothelialddsDESeq)

EndothelialRes <- results(EndothelialddsDESeq,name="Case_PD_vs_HC")

EndothelialRes_filter <- EndothelialRes[!is.na(EndothelialRes$padj),]

EndothelialRes_pvalfilter <- EndothelialRes_filter[EndothelialRes_filter$padj <= 0.05,]

EndothelialRes_pvalfilter

```

```{R}

EndothelialNormalisedCounts <- data.frame(counts(EndothelialddsDESeq, normalized = TRUE))

EndothelialNormalisedCounts <- cbind(rep(NA,length(EndothelialNormalisedCounts[,1])),EndothelialNormalisedCounts)

EndothelialNormalisedCounts <- cbind(rownames(EndothelialNormalisedCounts),EndothelialNormalisedCounts)

colnames(EndothelialNormalisedCounts)[c(1,2)] <- c("NAME","description")

write.table(EndothelialNormalisedCounts, "Files/EndothelialNormalisedCounts.txt",sep = "\t", row.names = FALSE,quote = FALSE)

```

Testing Intercept

```{R}
teeez <- results(EndothelialddsDESeq,name="Intercept")

teeezRes_filter <- teeez[!is.na(teeez$padj),]

teeezRes_pvalfilter <- teeezRes_filter[teeezRes_filter$padj <= 0.05,]

teeezRes_pvalfilter



```

Creating a function to run through GSE table creation 

```{R}

writeGSEtable <- function(cluster, SeuObj){
  tempframe <- subset(SeuObj, idents = cluster)
  tempframe <- tempframe[rowSums(tempframe@assays$RNA@counts) >= 10, ]
  tempframe <- tempframe@assays$RNA@counts
  coldata <- data.frame(as.vector(tempframe$case),as.vector(tempframe$sample_ID))
  row.names(coldata) <- colnames(tempframe)
  colnames(coldata) <- c("Case","Sample")
  tempframe <- t(aggregate.Matrix(t(tempframe), 
                       groupings = coldata, fun = "sum"))
  #check colnames to see if aggregation has worked and create a coldata table for DESeq2
  coldata_aggr <- data.frame(factor(str_extract(colnames(tempframe),"PD|HC")),factor(gsub("HC_|PD_","",colnames(tempframe))))
  colnames(coldata_aggr) <- c("Case","Sample")
  tempframe <- DESeqDataSetFromMatrix(countData = tempframe,
                       colData = coldata_aggr,
                       design = ~ Case)
  tempframe <- DESeq(tempframe)
  tempframe <- results(tempframe,name="Case_PD_vs_HC")
  tempframe <- tempframe[!is.na(tempframe$padj),]
  tempframe <- tempframe[tempframe$padj <= 0.05,]
  tempframe <- data.frame(counts(tempframe, normalized = TRUE))

tempframe <- cbind(rep(NA,length(tempframe[,1])),tempframe)

tempframe <- cbind(rownames(tempframe),tempframe)

colnames(tempframe)[c(1,2)] <- c("NAME","description")

write.table(tempframe, paste("Files/",deparse(substitute(cluster)),"_test.txt", sep = ""), sep = "\t", row.names = FALSE,quote = FALSE)
  
  
  
  
  
  
}


```










Astrocytes <- subset(Batch567_MTG, idents = "Astrocytes")

Idents(Astrocytes) <- "case"

#Performing DESeq differential expression analysis

#remove lowly expressed genes

Astrocytes_Filter <- Astrocytes[rowSums(Astrocytes@assays$RNA@counts) >= 10, ]

#grab counts, create aggrtable and aggregate based on sample and condition

Astrocyte_Counts <- Astrocytes_Filter@assays$RNA@counts

coldata <- data.frame(as.vector(Astrocytes_Filter$case),as.vector(Astrocytes_Filter$sample_ID))

row.names(coldata) <- colnames(Astrocyte_Counts)

colnames(coldata) <- c("Case","Sample")

Astrocyte_Counts_Aggr <- t(aggregate.Matrix(t(Astrocyte_Counts), 
                       groupings = coldata, fun = "sum"))

#check colnames to see if aggregation has worked and create a coldata table for DESeq2

colnames(Astrocyte_Counts_Aggr)

coldata_aggr <- data.frame(factor(str_extract(colnames(Astrocyte_Counts_Aggr),"PD|HC")),factor(gsub("HC_|PD_","",colnames(Astrocyte_Counts_Aggr))))

colnames(coldata_aggr) <- c("Case","Sample")

Astrocytedds <- DESeqDataSetFromMatrix(countData = Astrocyte_Counts_Aggr,
                       colData = coldata_aggr,
                       design = ~ Case)

AstrocyteddsDESeq <- DESeq(Astrocytedds)

resultsNames(AstrocyteddsDESeq)

AstrocytesRes <- results(AstrocyteddsDESeq,name="Case_PD_vs_HC")

AstrocytesRes_filter <- AstrocytesRes[!is.na(AstrocytesRes$padj),]

AstrocytesRes_pvalfilter <- AstrocytesRes_filter[AstrocytesRes_filter$padj <= 0.05,]

AstrocytesRes_pvalfilter

Performing original DEseq2 analysis to try and recreate error



```{R}
Astrocytes <- subset(Batch567_MTG, idents = "Astrocytes")

Idents(Astrocytes) <- "case"

#Performing DESeq differential expression analysis

#remove lowly expressed genes

Astrocytes_Filter <- Astrocytes[rowSums(Astrocytes@assays$RNA@counts) >= 10, ]

#grab counts, create aggrtable and aggregate based on sample and condition

Astrocyte_Counts <- Astrocytes_Filter@assays$RNA@counts

coldata <- data.frame(as.vector(Astrocytes_Filter$case),as.vector(Astrocytes_Filter$sample_ID))

row.names(coldata) <- colnames(Astrocyte_Counts)

colnames(coldata) <- c("Case","Sample")

Astrocytedds <- DESeqDataSetFromMatrix(countData = Astrocyte_Counts,
                       colData = coldata,
                       design = ~ Case)

AstrocyteddsDESeq <- DESeq(Astrocytedds)

resultsNames(AstrocyteddsDESeq)

AstrocytesRes <- results(AstrocyteddsDESeq,name="Case_PD_vs_HC")

AstrocytesRes_filter <- AstrocytesRes[!is.na(AstrocytesRes$padj),]

AstrocytesRes_pvalfilter <- AstrocytesRes_filter[AstrocytesRes_filter$padj <= 0.05,]

AstrocytesRes_pvalfilter
```






