#!/bin/bash
#BSUB -J test
#BSUB -o output/test-%J.out
#BSUB -e output/test-%J.err

# This is a sample script with specific resource requirements for
# **big** queue for single threaded, large memory jobs 
# Memory requirement should be specified if more than 16GB 
# Memory limit must also be set equal to memory reservation 
# if more than 40GB. 
# Maximum number of CPU cores 6.
# Copy this script and then submit job as follows:
# ---
# cd ~/lsf
# cp templates/bsub/example_big_6CPU_64GB.lsf .
# bsub < example_big_6CPU_64GB.lsf
# ---
# Then look in the ~/lsf/output folder for the script log
# that matches the job ID number

# Please make a copy of this script for your own modifications

#BSUB -q big
#BSUB -n 6
#BSUB -M 64000
#BSUB -R rusage[mem=64000]

# Some important variables to check (Can be removed later)
echo '---PROCESS RESOURCE LIMITS---'
ulimit -a
echo '---SHARED LIBRARY PATH---'
echo $LD_LIBRARY_PATH
echo '---APPLICATION SEARCH PATH:---'
echo $PATH
echo '---LSF Parameters:---'
printenv | grep '^LSF'
echo '---LSB Parameters:---'
printenv | grep '^LSB'
echo '---LOADED MODULES:---'
module list
echo '---SHELL:---'
echo $SHELL
echo '---HOSTNAME:---'
hostname
echo '---GROUP MEMBERSHIP (files are created in the first group listed):---'
groups
echo '---DEFAULT FILE PERMISSIONS (UMASK):---'
umask
echo '---CURRENT WORKING DIRECTORY:---'
pwd
echo '---DISK SPACE QUOTA---'
df .
echo '---TEMPORARY SCRATCH FOLDER ($TMPDIR):---'
echo $TMPDIR

# Add your job command here
module load cellranger/3.0.2
module load bcl2fastq2/2.19.1
module load bcl2fastq2/2.20.0
cellranger count --id=B0085 \
                   --transcriptome=/PHShome/mn516/software/premrna/GRCh38-1.2.0_premrna_oct12 \
                   --fastqs=/data/neurogen/scRNAseq/data/mohsen/cellranger_runs/mybcl/outs/fastq_path \
                   --sample=B0085 \
                   --localcores=8 \
                   --localmem=64 
