---
title: "Using PanglaoDB Markers and Method to Automate Cell Type Assignment"
output: html_document
---


library(Seurat)
library(cowplot)
library(ggplot2)
library(ggsci)
library(dplyr)
library(psych)
library(pheatmap)
library(harmony)
#library(clusterProfiler)
#library(org.Hs.eg.db)
library(DOSE)
library(GOSemSim)
library(enrichplot)
library(glmpca)
library(SeuratWrappers)

SeuratObject=readRDS("Files/GLMPCA_SeuratObject_Unassigned.rds")

DimPlot(SeuratObject, label = TRUE, repel = TRUE, pt.size = 0, label.size = 2.5)

ClusterExpMed <- function(ClusterIdent, SeuObj) {
  IdentObj <- subset(SeuObj, idents = ClusterIdent)
  MedExp <- apply(IdentObj@assays$RNA@data, 1, median)
  return(MedExp)
}

ExpVectorPerCluster <- lapply(sort(as.numeric(unique(SeuratObject@active.ident))),FUN = ClusterExpMed, SeuObj = SeuratObject)

ExpVectorPerClusterDF <- as.data.frame(do.call(cbind, ExpVectorPerCluster))

colnames(ExpVectorPerClusterDF) <- sort(unique(SeuratObject@active.ident))

PanglaoDB <- read.delim("~/Documents/Projects/Misc. Files/PanglaoDB_markers_27_Mar_2020.tsv", stringsAsFactors = FALSE)

PanglaoDBBrain <- PanglaoDB[PanglaoDB$organ %in% "Brain",]

PanglaoDBBrain <- PanglaoDBBrain[!PanglaoDBBrain$species %in% "Mm",]

#1 + sqrt((length(unique(PanglaoDBBrain$cell.type)) - sum(PanglaoDBBrain$official.gene.symbol == "TH"))/(length(unique(PanglaoDBBrain$cell.type)) - 1))

AssignGeneWeights <- function(Gene) {
  Weight <- 1 + sqrt((length(unique(PanglaoDBBrain$cell.type)) - sum(PanglaoDBBrain$official.gene.symbol %in% Gene))/(length(unique(PanglaoDBBrain$cell.type)) - 1))
  return(Weight)
}

GeneWeights <- unlist(lapply(unique(PanglaoDBBrain$official.gene.symbol), AssignGeneWeights))

GeneWeightsDF <- as.data.frame(cbind(unique(PanglaoDBBrain$official.gene.symbol), GeneWeights))

colnames(GeneWeightsDF) <- c("Gene","Weight")

PanglaoDBBrain <- PanglaoDBBrain[PanglaoDBBrain$official.gene.symbol %in% rownames(SeuratObject@assays$RNA@counts),]

GeneWeightsDF <- GeneWeightsDF[GeneWeightsDF$Gene %in% PanglaoDBBrain$official.gene.symbol,]

PanglaoDBBrain$GeneWeights <- GeneWeightsDF$Weight[match(PanglaoDBBrain$official.gene.symbol,GeneWeightsDF$Gene)]

PanglaoDBBrain[PanglaoDBBrain$official.gene.symbol == "TH",]

CellTypes <- unique(PanglaoDBBrain$cell.type)

PanglaoDBBrain$GeneWeights <- as.numeric(PanglaoDBBrain$GeneWeights)

CalculateCTA <- function(Cell, ClusterFrame, MarkerFrame) {
  CellMarkerFrame <- MarkerFrame[MarkerFrame$cell.type %in% Cell,]
  ClusterFrame$Genes <- rownames(ClusterFrame)
  CellClusterFrame <- as.data.frame(ClusterFrame[ClusterFrame$Genes %in% CellMarkerFrame$official.gene.symbol,])
  CellMarkerFrame <- CellMarkerFrame[order(match(CellMarkerFrame$official.gene.symbol,rownames(CellClusterFrame))),]
  CTAUnscaled <- CellClusterFrame[[1]]*CellMarkerFrame$GeneWeights
  CTAScore <- sum(CTAUnscaled/((length(CellMarkerFrame$official.gene.symbol))^1/3))
  return(CTAScore)
}

CellClusterAssignment=NULL
for (i in colnames(ExpVectorPerClusterDF)){
  ClusterColumn <- as.data.frame(ExpVectorPerClusterDF[[i]])
  rownames(ClusterColumn) <- rownames(ExpVectorPerClusterDF)
  colnames(ClusterColumn) <- "MedianExpression"
  CTAVector <- unlist(lapply(CellTypes, FUN = CalculateCTA, ClusterFrame = ClusterColumn, MarkerFrame = PanglaoDBBrain))
  names(CTAVector) <- CellTypes
  Assignment <- names(CTAVector[CTAVector == max(CTAVector)])
  CellClusterAssignment <- c(CellClusterAssignment,Assignment)
}

write.table(as.data.frame(CellClusterAssignment), file = "Files/CellClusterAssignment.tsv", quote = FALSE, row.names = FALSE, col.names = TRUE, sep = "\t")



